### ISSUE TITLE
Build stuck in `queued` status

### ISSUE THREAD

**Issue by farhan687** [travis-ci/travis-ci#10037]
Hi,

[This build](https://travis-ci.org/farhan687/docker-react/builds/420784481?utm_source=github_status&utm_medium=notification) is stuck in queued.
It's new repository.

How can I solve this?

Thanks.

**Comment by nfrechette** [comment]
I am also seeing similar behavior, I had a build partially complete, all linux platforms passed and completed but the OS X builds hung after completing, the log showed it terminated, but the build was still shown as "running". I cancelled the build after about 40mins even though it usually terminates in 15mins or so and pushed a new commit and now the new build is stuck as well in the queue.

New build:
https://travis-ci.org/nfrechette/acl/builds/420791066
Partial build:
https://travis-ci.org/nfrechette/acl/builds/420779763

**Comment by anandmnair** [comment]
Hello , 
I am also facing the similar issues.  [This Build](https://travis-ci.org/societe-generale/rabbitmq-advanced-spring-boot-starter/builds/420790732) is showing the status as queued, and no progress so far.

**Comment by ahkela21** [comment]
I'm having the similar issues. #[Build](https://travis-ci.org/UtarSccGroupProject/html/builds/420788423)

**Comment by mysterycommand** [comment]
I think I am also currently being affected by this issue. I'm not sure what the relationship between Travis' UI and GitHub's status UI is, but both my PR and push jobs show as "queued" in both UIs. However, digging into the network tab a little bit it looks like the associated `log.txt` is being updated correctly and shows a successful/passing build:

Travis PR build:
https://travis-ci.org/fartts/fartts/builds/420786624
Travis PR build log:
https://api.travis-ci.org/v3/job/420786625/log.txt

Travis push build:
https://travis-ci.org/fartts/fartts/builds/420786622
Travis push build log:
https://api.travis-ci.org/v3/job/420786623/log.txt

Github status UI:
<img width="694" alt="screenshot 2018-08-26 12 53 42" src="https://user-images.githubusercontent.com/810398/44630652-1ecb5800-a92f-11e8-9c39-b1f3a03d4894.png">

**Comment by NapsterInBlue** [comment]
Piling on with [my build](https://travis-ci.org/NapsterInBlue/notes/builds/420800169).

**Comment by farhan687** [comment]
My issue is resolved, works fine now!

**Comment by NapsterInBlue** [comment]
Weird, same!

**Comment by iamdevlinph** [comment]
Only the pull request builds seems to be fine. Still having an issue with the default branch build.

**Comment by mysterycommand** [comment]
Mine also started working again out of the blue.

**Comment by wahengchang** [comment]
ZZZzzzzz

waiting for the same issue in 2019
