### ISSUE TITLE
Slack notifications: add support for on_success and on_failure

### ISSUE THREAD

**Issue by mattab** [travis-ci/travis-ci#2894]
The goal of this issue is to add support for `on_success` and `on_failure` for Slack notifications.

**Steps to reproduce:**
 * Add notification to Slack eg. https://github.com/piwik/piwik/blob/master/.travis.yml#L167-L172
```
slack:
rooms:
- piwik:x
on_success: change
on_failure: change
```
 * Commit a change to repo

**Result:**
 * Expected:  get notifications in Slack only when build status changes
 * Got instead: notifications is sent to Slack after each build

**Comment by jszwedko** [comment]
:+1: to also checking for `change` rather than `:change` since the documentation only mentions `change`.

**Comment by jszwedko** [comment]
Like @markdorison I'm still getting notifications for both `:change` and `change`.

**Comment by gruppjo** [comment]
Just as @markdorison and @jszwedko I'm getting nottifications always despite `:change` and `change`. This is my `.travis.yml` https://github.com/mwaylabs/generator-m/blob/master/.travis.yml#L8-L12

**Comment by paulyoung** [comment]
We stopped receiving Slack notifications after I added `on_success` and `on_failure` as below.

```yaml
notifications:
  slack:
    secure: ...
    on_success: change
    on_failure: always
```

Using `:change` and `:always` instead makes no difference.

**Comment by viggeh** [comment]
Same experience as @gruppjo et al. We are also always receiving success notifications despite setting it to ```:change``` or ```change```

Here's the config:
```yaml
notifications:
  slack:
    on_success: :change
    on_failure: always
    rooms:
    - secure: securestring
```

**Comment by gyoshev** [comment]
@joshk Are there any updates on this? `on_success` does not accept any parameters (neither `never`, `change`, or `:change`). Here is [our travis.yml](https://github.com/telerik/kendo-ui-core/blob/master/.travis.yml#L13-L15)

**Comment by joshk** [comment]
We will look into fixing this next week. I'm sorry for the delays in getting this addressed.

**Comment by crummy** [comment]
Is there a workaround beyond disabling slack notifications entirely?

**Comment by BanzaiMan** [comment]
I just tested the `on_success` and `on_failure` with both string and symbol, and they all worked as expected. This is the case with .com and .org.

**Comment by BanzaiMan** [comment]
I'm closing this now. `on_success` and `on_failure` should be working as described.

**Comment by barbeau** [comment]
Is anyone else still seeing this issue?

For the life of me I can't get the Slack notifications to work with `on_success` and `on_failure` included.  

This configuration works for me:

* Unencrypted token, *without* `on_success` and `on_failure`

These don't:

* Unencrypted token, with `on_success` and `on_failure`
* Encrypted token (with or without `on_success` and `on_failure`)

Here are the different configurations I've tried that don't result in any notifications:

~~~
notifications:
  slack:
    rooms:
      secure: GpZ8w7KRmzrZB4t2UqWCG98L23H9qbOdqYVM483XwdXbTwqzRrVjRvRzjqV9VN0XyqBW57a9nJSzmtmNZZxbjpKop74Khj+zhH0kbkfWJpTy7RrXeJZBSYqL20I5qwW4ZiZFlNUQgGE/LBYerUvsUxrAm+5MfiBWA9dctTaqlgM=
    on_success: change
    on_failure: always
~~~

~~~
notifications:
  slack:
    rooms:
      - onebusaway:DuVMFUTB2Y7YXRBIvLq7sqtR
    on_success: change
    on_failure: always
~~~

~~~
notifications:
  slack: onebusaway:DuVMFUTB2Y7YXRBIvLq7sqtR
    on_success: change
    on_failure: always
~~~

~~~
notifications:
  slack:
    rooms:
      - onebusaway:DuVMFUTB2Y7YXRBIvLq7sqtR#android
    on_success: change
    on_failure: always
~~~

What am I missing?

Here's the full .travis.yml:
https://github.com/OneBusAway/onebusaway-android/blob/travisSlack3/.travis.yml

**Comment by BanzaiMan** [comment]
@barbeau It appears that you are trying to send notifications with `on_success: change`, but when this condition is met (for example, from [build #956](https://travis-ci.org/OneBusAway/onebusaway-android/builds/94452520) to [build #966](https://travis-ci.org/OneBusAway/onebusaway-android/builds/94454767)) you had a secure key, which I believe is incorrectly encrypted. All others don't seem to trigger notifications, or had errors with `.travis.yml`.

Try:

```yaml
notifications:
  slack:
    on_success: always
```

and encrypt with:

    travis encrypt -r OneBusAway/onebusaway-android --org

and use STDIN to encrypt data.

**Comment by barbeau** [comment]
@BanzaiMan Thanks for the tip!  Seems like it was an incorrectly encrypted key.

On both Windows and Mac, this command is generating keys that don't result in notifications (even when using `on_success: always`):

`travis encrypt "onebusaway:xxxxxxx" --add notifications.slack.rooms`

We finally got notifications working by using the encrypt command you specified and using STDIN, and running on a Mac:

`travis encrypt -r OneBusAway/onebusaway-android --org`

Here's the working build that resulted in a notification:
https://travis-ci.org/OneBusAway/onebusaway-android/builds/94669527

For the record, assuming that we wanted to use an unencrypted key, what is the correct syntax in `.travis.yml` for that configuration?

**Comment by BanzaiMan** [comment]
@barbeau Any of the last 3 you showed in https://github.com/travis-ci/travis-ci/issues/2894#issuecomment-161445087 should work.

**Comment by tir38** [comment]
I'm still getting this problem. No matter what I get success notifications in slack. This is my setup:

```
notifications:
  email: false
  slack:
    on_failure: always
    on_success: never
    secure: XXXX
```

It doesn't matter if I set `on_success:` to `never` or `change`. Am I missing something?

**Comment by barbeau** [comment]
Here's the config that's working for us:
https://github.com/OneBusAway/onebusaway-android/blob/master/.travis.yml#L50

**Comment by tir38** [comment]
I mimicked your format and I'm getting the same problems. =(

**Comment by barbeau** [comment]
@tir38 Are you posting notifications to a particular Slack room?  We are.

**Comment by vcarel** [comment]
Why this issue is closed ?
Here is my configuration and I get no notification **at all**
```
notifications:
  slack:
    secure: ...
    on_success: change
    on_failure: always
```

When I remove on_success and on_failure, I get notifications. So my secure key is correct...

**Comment by BanzaiMan** [comment]
@vcarel Because your configuration is faulty. Try:

```yaml
notifications:
  slack:
    rooms:
      - secure: ...
    on_success: change
    on_failure: always
```

This is basically the example shown in https://docs.travis-ci.com/user/notifications/#Slack-notifications.

**Comment by vcarel** [comment]
@BanzaiMan yes, when I comply to the doc, it works. Thanks ! :-)
However the command ```travis encrypt "xxx:yyy" --add notifications.slack``` issues the above configuration, which *works* unless on_success and on_failure are defined.
Honestly this is kindof wrong...

**Comment by BanzaiMan** [comment]
There are UX problems (or a bug), to be sure. `travis encrypt --add` assumes that there is nothing in the target, and that nothing will be added to the target.

**Comment by kevinquillen** [comment]
When I try whats in the docs and [this comment](https://github.com/travis-ci/travis-ci/issues/2894#issuecomment-268286843), I don't get any failure notifications to the room. Is `on_start` supported by slack?

**Comment by BanzaiMan** [comment]
@kevinquillen That's curious. Please send email to support@travis-ci.com with details. Thanks.

**Comment by damianobarbati** [comment]
@barbeau how did you solve?
https://github.com/travis-ci/travis-ci/issues/6528#issuecomment-310325277

I tried the following encrypting ways, no success so far:
```
travis encrypt -r quant-01/quant01 --pro "quant01:<token>"
travis encrypt -r quant-01/quant01 --pro "quant01:<token>#builds"
travis encrypt -r quant-01/quant01 "quant01:<token>"
travis encrypt -r quant-01/quant01 "quant01:<token>#builds"
```
.travis.yml attempt#1
```
notifications:
    email:
        recipients: damiano.barbati@gmail.com
        on_success: always
        on_failure: always
    slack:
        secure: "<secret>" 
        on_success: always
        on_failure: always
```

.travis.yml attempt#2
```
notifications:
    email:
        recipients: damiano.barbati@gmail.com
        on_success: always
        on_failure: always
    slack:
        rooms:
            - secure: "<secret>" 
        on_success: always
        on_failure: always

```

**Comment by barbeau** [comment]
@damianobarbati Here's the configuration that was working for us:
https://github.com/OneBusAway/onebusaway-android/blob/7a88700b68864dd780cb4900d7a07f3cd7411a8c/.travis.yml#L50

It's not in the current master branch - I ended up killing build result notifications because it was too much chatter and was drowning out other discussions.
