### ISSUE TITLE
Better history of build/job restarts

### ISSUE THREAD

**Issue by comjf** [travis-ci/travis-ci#2993]
Add the ability to download a log (or otherwise view) of build restarts including individual job restarts.

Record time, commit/PR, who restarted it, and any other applicable information

This will greatly help us with our audits on test quality and average time through travis.

**Comment by lbergelson** [comment]
This is important to us because we use build reruns to diagnose issues with dependencies and changing build environment.  Accessing prior versions of the same build is important.

**Comment by BanzaiMan** [comment]
I'm noting here that this is on our roadmap, but do not have ETA.

**Comment by mheffner** [comment]
Adding a :+1: for this. Oftentimes I'd like to go back and fix some transient/flapping error in previous logs, but urgency to get a successful build means those failed logs are lost.

**Comment by laurent-le-graverend** [comment]
👍

**Comment by jacob-carlborg** [comment]
I don't see anything indicating that this has been fixed. Neither as information from Travis or when I just checked by restarting a job.

**Comment by comjf** [comment]
Same... Still don't see a resolution on this. We'd still like this feature... Until then we'll just continue to email you guys to pull back these stats for us (admittedly not very frequently).

**Comment by jakirkham** [comment]
This is unresolved AFAIK.

**Comment by blimmer** [comment]
👍

**Comment by DrTorte** [comment]
We do still have this planned for in the UI/UX sometime in the future, though don't have any date to commit to yet. It hasn't been forgotten though!

If anyone needs their logs, you are welcome to email us and we'll fetch them for you, as we have them available on our end.
