### ISSUE TITLE
On private Mac builds with the Xcode 6.3 image, use of caching utility yields warnings about `$PATH`

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4207]
```
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin' is not at first place,

         usually this is caused by shell initialization files - check them for 'PATH=...' entries,

         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',

         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p643'.
```

**Comment by BanzaiMan** [comment]
This does not happen on the default or the Xcode 6.4 image, but does on the Xcode 6.3.

**Comment by BanzaiMan** [comment]
I looked at `$PATH` value for the 6.3 image, but I am not sure why this warning is printed.

```sh-session
$ Installing caching utilities
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p643'.
⋮
$ echo $PATH
/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/travis/.rvm/rubies/ruby-2.0.0-p643/bin:/Users/travis/.rvm/bin:/Users/travis/bin:/Users/travis/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by jacebrowning** [comment]
@BanzaiMan Is there a place I can see all the available options for `osx_image`? I assume the 6.4 images is `beta-xcode6.4`?

**Comment by BanzaiMan** [comment]
@jacebrowning Correct. You can try `beta-xcode6.4`. We don't have a list of valid values for `osx_image` at the moment.

**Comment by BanzaiMan** [comment]
@jacebrowning Correction. The list is available here: http://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-ci/issues/4864 reports that this now happens on the Xcode 6.4 image as well.

**Comment by jacebrowning** [comment]
I get a similar issue in the `xcode7` images:

```
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p643'.
```

This does not seem to affect the caching behavior.

**Comment by zer0main** [comment]
I get a similar issue on a standard (linux) build.
When Travis reaches the deploy stage of build, the following warning is printed:

```
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
```

I don't change PATH so the problem seems to be on your side.
Link to build log: https://travis-ci.org/zer0main/battleship/jobs/101417059

See also: https://github.com/travis-ci/dpl/issues/388

**Comment by fukanchik** [comment]
One more (centos 7): https://travis-ci.org/fukanchik/cdm-pythonparser/builds/103244130

**Comment by BanzaiMan** [comment]
Interesting find on the Linux images showing this issue. Are there any ill effects besides these warnings?

**Comment by fukanchik** [comment]
I do not know if they cause this, but despite the following printed, the files were not attached to the GH release:
```
Installing deploy dependencies
Fetching: addressable-2.3.8.gem (100%)
Successfully installed addressable-2.3.8
Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.9.2.gem (100%)
Successfully installed faraday-0.9.2
Fetching: sawyer-0.6.0.gem (100%)
Successfully installed sawyer-0.6.0
Fetching: octokit-4.2.0.gem (100%)
Successfully installed octokit-4.2.0
5 gems installed
Fetching: mime-types-2.99.gem (100%)
Successfully installed mime-types-2.99
1 gem installed
dpl.2
Preparing deploy
Logged in as Sergey Fukanchik
Deploying to repo: fukanchik/cdm-pythonparser
Current tag is: v0.6
dpl.3
Deploying application
```

**Comment by BanzaiMan** [comment]
@fukanchik I don't think `file:` parameter takes the glob.

**Comment by fukanchik** [comment]
1. Do you know what should i do to deploy RPMs of variable name?
2. i was relying on https://github.com/travis-ci/dpl#options-22 where i see *file_glob*

**Comment by BanzaiMan** [comment]
@fukanchik You're right. I'll have to look at that, but I believe this is a separate issue from the RVM warning.

**Comment by fukanchik** [comment]
Ok. Do you want me to open another ticket?

**Comment by BanzaiMan** [comment]
@fukanchik Yes, please.

**Comment by fukanchik** [comment]
@BanzaiMan nevermind, i was able to upload a release to github after fixing a problem in my script.

**Comment by BanzaiMan** [comment]
This should be fixed now.

**Comment by lasconic** [comment]
I still see it here https://travis-ci.org/lasconic/MuseScore/builds/127285968#L1559

**Comment by BanzaiMan** [comment]
Interesting. looks like it's getting hit by an RVM issue that prevents the fix from working correctly. :-/

**Comment by lasconic** [comment]
Forget it. I did put something before rvm in the PATH. Thus the error, I changed the PATH to put rvm back and it proceeds. It fails because of the 180s timeout on `casher push` but that's another issue... 
https://travis-ci.org/lasconic/MuseScore/builds/127306512#L1559

**Comment by BanzaiMan** [comment]
Closing now.
