### ISSUE TITLE
Failed to find Build Tools revision 23.0.2

### ISSUE THREAD

**Issue by schildbach** [travis-ci/travis-ci#5036]
In the .travis.yml I recently switched the Android build-tools version to 23.0.2, like this:

```
 android:
   components:
-    - build-tools-23.0.1
+    - build-tools-23.0.2
     - android-23
     - extra-android-m2repository
```

Now it fails:

```
FAILURE: Build failed with an exception.

* What went wrong:

A problem occurred configuring project ':mapsforge-map-android'.

> failed to find Build Tools revision 23.0.2
```

This is the affected build: https://travis-ci.org/schildbach/mapsforge/builds/88498248

**Comment by BanzaiMan** [comment]
Is it valid?

https://travis-ci.org/schildbach/mapsforge/jobs/88498249#L123

```
Error: Ignoring unknown package filter 'build-tools-23.0.2'
Warning: The package filter removed all packages. There is nothing to install.
         Please consider trying to update again without a package filter.
```

**Comment by schildbach** [comment]
What do you mean by "valid"? It's a released version, yes.

**Comment by schildbach** [comment]
I have this section in my locally cached repository.xml:

```
    <sdk:build-tool>
        <!-- Generated at Thu Oct 22 08:42:51 2015 from git_mnc-dev @ 2355899 -->
        <sdk:revision>
            <sdk:major>23</sdk:major>
            <sdk:minor>0</sdk:minor>
            <sdk:micro>2</sdk:micro>
        </sdk:revision>
        <sdk:archives>
            <sdk:archive>
                <sdk:size>38217626</sdk:size>
                <sdk:checksum type="sha1">fc3a92c744d3ba0a16ccb5d2b41eea5974ce0a96</sdk:checksum>
                <sdk:url>build-tools_r23.0.2-windows.zip</sdk:url>
                <sdk:host-os>windows</sdk:host-os>
            </sdk:archive>
            <sdk:archive>
                <sdk:size>39071201</sdk:size>
                <sdk:checksum type="sha1">8a9f2b37f6fcf7a9fa784dc21aeaeb41bbb9f2c3</sdk:checksum>
                <sdk:url>build-tools_r23.0.2-linux.zip</sdk:url>
                <sdk:host-os>linux</sdk:host-os>
            </sdk:archive>
            <sdk:archive>
                <sdk:size>38060914</sdk:size>
                <sdk:checksum type="sha1">482c4cbceef8ff58aefd92d8155a38610158fdaf</sdk:checksum>
                <sdk:url>build-tools_r23.0.2-macosx.zip</sdk:url>
                <sdk:host-os>macosx</sdk:host-os>
            </sdk:archive>
        </sdk:archives>
        <sdk:uses-license ref="android-sdk-license"/>
    </sdk:build-tool>
```

This causes the release to appear in the Android SDK Manager.

**Comment by schildbach** [comment]
The file is fetched from here: https://dl-ssl.google.com/android/repository/repository-11.xml
But in the Travis build, an older file was used: https://dl-ssl.google.com/android/repository/repository-10.xml

**Comment by BanzaiMan** [comment]
@schildbach Thanks for the info. We'll investigate.

**Comment by BanzaiMan** [comment]
@gildegoma Do you know how we can fetch the new XML file?

**Comment by BanzaiMan** [comment]
With @gildegoma's help, I confirmed that adding `tools` to the components will address this issue.

```yaml
android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
⋮
```

https://travis-ci.org/BanzaiMan/travis_production_test/builds/88967451#L280-L282

This behavior is documented in http://docs.travis-ci.com/user/languages/android/#Overview.

I'm closing this issue optimistically, but if you continue to see problems, do let us know.

**Comment by schildbach** [comment]
Thanks, this fixes the issue for me too. However, it has the downside that the build is not fully reproducable any more since `tools` just means *latest* SDK tools, rather than a specific version. Is there a way to specify 24.4.1? (I tried `tools-24.4.1` but it fails.)

Can you consider incrementing the tools default to 24.4.1? 24.0.0 is already a year old!

**Comment by BanzaiMan** [comment]
That's good news. The `tools` version is a separate issue. Could you open a new one? Thank you.

**Comment by schildbach** [comment]
Done: #5048 #5049

**Comment by nwalters512** [comment]
Even with `tools`, my build is still failing with the same error message as the original reporter. The relevant contents of my `.travis.yml` are below

```
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
⋮
```

Any idea what gives?

**Comment by k3b** [comment]
I had the same issue

@BanzaiMan wrote

   > I confirmed that adding tools to the components will address this issue.
   > android:
   >    components:
   >     - tools
   > ...
   > This behavior is documented in http://docs.travis-ci.com/user/languages/android/#Overview.

The link documents that there is a "tools" setting. But i found no info that "tools" is neccessary to use 23.0.2. Is it possible to add this info to the documentation ?
