### ISSUE TITLE
System boto incompatible with Python 3.x

### ISSUE THREAD

**Issue by migurski** [travis-ci/travis-ci#5246]
Partial [output from a failing test](https://travis-ci.org/openaddresses/machine/jobs/95292169):

```
  File "/home/travis/build/openaddresses/machine/openaddr/__init__.py", line 17, in <module>
    from boto import connect_s3
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/imp.py", line 180, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/imp.py", line 119, in load_source
    _LoadSourceCompatibility(name, pathname, file).load_module(name)
  File "/usr/share/google/boto/boto_plugins/compute_auth.py", line 64
    except (urllib2.URLError, urllib2.HTTPError, IOError), e:
                                                         ^
SyntaxError: invalid syntax
The command "python setup.py test" exited with 1.
```

Boto project [has closed this issue](https://github.com/boto/boto/issues/3263), indicating that boto is not intended to be Python 3.x compatible. I believe it is a Travis error that `boto/boto_plugins/compute_auth.py` is loaded. [These tests worked previously](https://travis-ci.org/openaddresses/machine/jobs/93849953).

**Comment by BanzaiMan** [comment]
So, we are running on GCE, and it appears that the image comes with boto pre-installed. Is it possible to change the search paths so that `/usr/share/…` is ignored?

**Comment by migurski** [comment]
Is GCE a new thing? `/usr/share/google` is a weird search path. I could probably tweak it but this really seems like a bug to me.

**Comment by migurski** [comment]
…I just saw a build pass on https://github.com/openaddresses/machine/pull/262, so maybe this issue has been fixed. However, I’m seeing a different error that’s making it hard to verify what’s happened: https://github.com/travis-ci/travis-ci/issues/5273

**Comment by BanzaiMan** [comment]
Might be related to #5269.

**Comment by hellerve** [comment]
Just a heads-up: This problem still persists for us (but only if we use `dist: trusty`).

**Comment by BanzaiMan** [comment]
This might be a different manifestation of #5326. Could you try the $PATH manipulation shown there?

**Comment by jamesls** [comment]
I'm trying to dig into what's going on (I work on boto), and I don't know if we can fix this completely on boto's side.  Here's what's going on:

boto has a feature that allows for plugins to be loaded at runtime (import time in this case).  These plugins can be configured in the boto config file.  Boto also has a global config file (`/etc/boto.cfg`) it will try to load.

What's likely happening:

* Somewhere in people's code they have "import boto"
* This looks for a list of plugins to import.  On the machine, the file `/etc/boto.cfg` has [these contents](https://travis-ci.org/jamesls/boto/jobs/98225679#L606):
```
[Plugin]
plugin_directory = /usr/share/google/boto/boto_plugins
```
* One of these plugins is `/usr/share/google/boto/boto_plugins/compute_auth.py` which appears to be preinstalled on the machine.
* Boto will try to import this plugin.  This plugin is not python3 compatible so it will immediately fail.

Options

An easy workaround is to just override the config file by setting `BOTO_CONFIG` to [some bogus value](https://travis-ci.org/jamesls/boto/jobs/98225679#L652).  This is probably what I'll have to do in boto/boto to get the builds passing in the short term.

Long term, I don't actually know what compute_auth.py does, but either a) It get's updated to be compatible with py3 or b) that contents of `/etc/boto.cfg` are updated to remove the `plugin_directory` line.

Let me know if there's anything we can do on boto's side to help.

**Comment by bivald** [comment]
compute_auth.py handles default authentication for Google Cloud Storage using Google Service Accounts (i.e aims to make boto "just work" out of the box on Compute Engine Instances). I've made a pull request to make compute_auth.py python3 compatible which should solve this issue once and for all. I'm using my patched version now on GCE and it works well for both python2 and 3

https://github.com/GoogleCloudPlatform/compute-image-packages/pull/213

**Comment by olt** [comment]
This issue is still present. I had to use the `BOTO_CONFIG` workaround to fix the builds.
See https://github.com/mapproxy/mapproxy/blob/a039bf6624a25d5dbbdfb03cea22d03148b02d17/.travis.yml
