### ISSUE TITLE
Segmentation fault (core dumped) vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

### ISSUE THREAD

**Issue by arcanedev-maroc** [travis-ci/travis-ci#5323]
Hi everyone,

I have the same issue in one of my packages : https://travis-ci.org/ARCANESOFT/Auth/jobs/97489752

It says: `../home/travis/build.sh: line 45:  3977 Segmentation fault      (core dumped) vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover`

Even that PHP 7 is stable now.

This one works perfectly : https://travis-ci.org/ARCANESOFT/Foundation/jobs/97486050

**Comment by BanzaiMan** [comment]
Where is `vendor/bin/phpunit` coming from?

**Comment by arcanedev-maroc** [comment]
composer.json => packagist

**Comment by BanzaiMan** [comment]
https://phpunit.de/ suggests that PHPUnit 4.8.x, which composer is choosing, is not supported by PHP 7. I find it strange that it used to work on the same repo. https://travis-ci.org/ARCANESOFT/Auth/jobs/97071052

Is it possible to use PHPUnit 5.1 and see if it helps?

**Comment by arcanedev-maroc** [comment]
I've already set that (https://github.com/ARCANESOFT/Auth/blob/master/composer.json#L27).

There are some dependencies that requires PHPUnit `v4.*` and i can't force composer to resolve it.

**Comment by arcanedev-maroc** [comment]
Hi @BanzaiMan,

I think the issue is solved with a god's will :pray:. .

Thanks and Praise the sun \\o/.

**Comment by w4** [comment]
For anybody else getting this issue who is trying to generate code coverage, Xdebug is the issue as it does not yet support. You can solve the issue by instead using [phpdbg](http://phpdbg.com/) to generate coverage, which is in the PHP core.

*Even if you get Xdebug working - I highly recommend you switch to phpdbg, it is much faster*

Disable Xdebug by adding `phpenv config-rm xdebug.ini` to your before_script. Then in your `script`, change `php` to `phpdbg -qrr`. Your `script` should look something like this:

    phpdbg -qrr vendor/bin/phpunit --coverage-clover build/logs/clover.xml

**Comment by Oliboy50** [comment]
@w4 Awesome!

I was still having the same issue (even if xdebug is supposed to support php7 now)... but this phpdbg stuff just saved my day :)

Thanks 👍

**Comment by w4** [comment]
Not a problem @Oliboy50, glad you got it working 😄

**Comment by arcanedev-maroc** [comment]
Hi @BanzaiMan,

Can you check this job : https://travis-ci.org/ARCANEDEV/Stripe/jobs/123563893

**Comment by BanzaiMan** [comment]
@arcanedev-maroc I'm sorry, but I can't help much with PHP nightly build failures.

**Comment by arcanedev-maroc** [comment]
OK, thanks anyway.
