### ISSUE TITLE
When using gemsets - cocoapods fails to run

### ISSUE THREAD

**Issue by jcampbell05** [travis-ci/travis-ci#5654]
Currently Travis CI detects that I have a RVM Gemset.

The gems are installed correctly however when pod install is ran it fails to find it.

- I've manually overriden the install method but this results in no caching and long build times which is unacceptable.
- There is no way to ignore the gemfile to see if not using that fixes the problem.
- I've manually forced RVM to use the gemfile to see if that works but to no avail.

**Comment by BanzaiMan** [comment]
Could you point to a build log URL that shows the problem? Since this is a private repo, you may want to email us at support@travis-ci.com instead.

**Comment by jcampbell05** [comment]
@BanzaiMan I've tried emailing but the 2 day feedback loops are just too slow, do you know if I would be able to setup a call so we can debug it ?

**Comment by BanzaiMan** [comment]
We have deployed the fix for #3239 this week that allows the use of special caching directives with overridden `install`. Have you tested it?

**Comment by jcampbell05** [comment]
@BanzaiMan had a go, bundle uses the cache but pods still fail. 

Interestingly fastlane works if I use `bundle exec` as well as cocoapods when ran under fastlane (As fastlane uses `bundle exec`). so if the install command was updated so it was `bundle exec pod install` instead of `pod install` then gemsets would work fully :)

**Comment by BanzaiMan** [comment]
@jcampbell05 OK. Let's continue our discussion on the email thread, then. I feel that the issue at hand is a bit hazy at the moment, and very difficult to track here. Is it OK to close this? (We'll open a separate issue if the investigation leads to a well-defined bug to squash.)

**Comment by BanzaiMan** [comment]
The investigation led to https://github.com/travis-ci/travis-ci/issues/5662. I am going to close this one in favor or a more focused issue.

**Comment by jcampbell05** [comment]
Great, let me know how I can help.
