### ISSUE TITLE
Unknown error (Mac OS build)

### ISSUE THREAD

**Issue by PMassicotte** [travis-ci/travis-ci#5673]
Hi @craigcitro, @hadley, and @jimhester.

Two of my packages can't be build on Travis (Mac OS build)

https://travis-ci.org/PMassicotte/cdom/jobs/110902254

I have a very simple yml file created using `devtools::add_travis()`:

```
language: r
warnings_are_errors: true
sudo: required

os:
  - linux
  - osx
```

The build works perfectly fine on Linux and on Windows (using Appveyor). I manually restarted the build few times without success.

Regards,
Philippe

**Comment by BanzaiMan** [comment]
Seems to be the same issue as https://github.com/craigcitro/r-travis/issues/174.

**Comment by jimhester** [comment]
I believe this can be closed, they have a later build which succeeded (https://travis-ci.org/PMassicotte/cdom/jobs/113645347) and the underlying cause has been fixed.

**Comment by PMassicotte** [comment]
I still do not know what caused the error. I didn't changed anything. But since it's now succeeding I guess I'll close it.
