### ISSUE TITLE
PHP cannot use SSL

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-ci#6339]
There was a report that PHP cannot use SSL/TLS with php's curl. Normal `curl` does work.

The error: `string(76) "gnutls_handshake() failed: A TLS packet with unexpected length was received."`

This happens with a wide array of SSL options.

Log: https://travis-ci.org/joepvd/travis-experiment/jobs/146108809
Test case (courtesy @TextControl): https://github.com/joepvd/travis-experiment/tree/17a779c65604f2df07d9227811ed7970f4bc593a

**Comment by BanzaiMan** [comment]
In http://stackoverflow.com/a/38429611/136333, @jonathanmaron reports that the official Ubuntu packages (`php5-cli` and `php5-curl`) are sufficient to have this issue resolved.

Our binaries are compiled using https://github.com/php-build/php-build with our build process shown in https://github.com/travis-ci/php-src-builder (in particular https://github.com/travis-ci/php-src-builder/blob/default/bin/compile). The process needs to be updated (either via `php-build` or via our compile script), but I have very few ideas as to how to make that happen.

**Comment by rdok** [comment]
@joepvd have you proceeded with rebuilding the PHP package? I've been having the same problem. https://travis-ci.org/rdok/elasticemail-php/jobs/157308268

@BanzaiMan  I [did try](https://travis-ci.org/rdok/elasticemail-php/builds/157312860) @jonathanmaron suggestion. I did not manage to make it work. Moreover, this [suggestion](http://stackoverflow.com/a/38429611/2790481) is viable only for PHP 5.5 according to @jonathanmaron

Thanks in advance!

**Comment by hohl** [comment]
I'm using php7-curl and got the same issue. So this issue seems not to be related to PHP 5.5 only. Does anybody ever found a workaround for this issue?

**Comment by BanzaiMan** [comment]
My understanding is that the PHP binary will have to be recompiled (I indicated the process in the comment above), but I don't know how to make that happen.

**Comment by hohl** [comment]
Yes, I had the same issue on my local (macOS) testing machine where I used the preinstalled PHP7 and cURL. Since I got the same issue I updated cURL and then recompiled PHP which solved the issue.

**Comment by andig** [comment]
For me this issue has started just a few days ago. Before that PHP builds were going fine.

**Comment by Stafox** [comment]
Got the same, guys.
Builds on php 7.0 and hhvm always passed successfully. But on php 5.5, 5.6 and 7.1 with error:
`cURL error 35: gnutls_handshake() failed: A TLS fatal alert has been received` 
After 7-8 restarts the build on I got green light on php 5.5 only.

Whilst I had writing this message all builds have passed successfully

**Comment by Kolyunya** [comment]
I can confirm the issue for the `PHP 5.4` environment. `5.5`, `5.6`, `7.0`, `7.1`, `hhvm` and `nightly` are just fine. Looking forward for a fix. Thank you!

**Comment by jonnybarnes** [comment]
I still get this issue if I don’t use a non-https endpoint with sensiolab’s security checker.

**Comment by alexfinnarn** [comment]
Yeah, I don't think this issue is fixed...

I only have 

```yaml
language: php
sudo: false

php:
  - '7.1'
```

in my .travis.yml file relating to PHP. I'm not sure how this works for other people other than the HTTPS to HTTP URL switching I see in some referenced commits above.

**Comment by rpkamp** [comment]
I just ran into this problem yet again.

@joepvd any update on this? It's been more that a year now.

**Comment by markdza** [comment]
Still an issue. Can we get a fix for this please? Our case is with issue #8912 (above)

**Comment by markdza** [comment]
Can this issue be resolved please?

**Comment by BanzaiMan** [comment]
Unless someone can suggest improvements on the process I described earlier (https://github.com/travis-ci/travis-ci/issues/6339#issuecomment-234380010), I am afraid there is no progress on this issue.

**Comment by DivineOmega** [comment]
I'm also experiencing this issue. Is there any progress on this, and/or is there anything I can do to help?

**Comment by DivineOmega** [comment]
It is worth noting that the current `hhvm` build does not suffer from this issue. I've change my `.travis.yml` file to remove all PHP versions and just use `hhvm` temporarily.

```yml
language: php
dist: trusty
php:
  - 'hhvm'
install:
  - composer update
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v
```

**Comment by Webonaute** [comment]
PHP 7.1 with Symfony 3.2 : cURL error 35: gnutls_handshake() failed... I have also this issue. in local on my laptop with same config (but PHP package coming from brew) it work perfectly.

**Comment by rpkamp** [comment]
I have found that if you have control over the URL to be called there is a workaround using Docker and an nginx reverse proxy. I've set it up as follows and that works, because PHP is connecting using HTTP and Nginx is actually doing the HTTPS connection, and that works.

In the example below I'm assuming you want to connect to `example.com` from PHP using HTTPS.

.travis.yml
```yml
services:
  - docker

addons:
  hosts:
    - example.com

before_install:
  - docker pull nginx:alpine
  - docker run -v $(pwd)/.travis/nginx.conf:/etc/nginx/nginx.conf:ro -d -p 80:80 nginx:alpine
```

then you need a file `.travis/nginx.conf`:

```conf
events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name example.com;

        location / {
            proxy_pass https://example.com;
        }
    }
}
```

This looks completely weird but the effect is that all requests with the HTTP `Host` header `example.com` will be forwarded to the actual `example.com`, since the docker container doesn't know anything about the host addon Travis is using.

So basically your traffic will be flowing like this:

```
+----------------------------------------+
|                                        |
| +------+        +------------------+   |   +--------------+
| |      +-------->                  +---+--->              |
| | PHP  | http   | Nginx in Docker  | https | example.com  |
| |      <--------+                  <---+---+              |
| +------+        +------------------+   |   +--------------+
|                                        |
|           Tra^is en^ironment           |
+----------------------------------------+
```

So in PHP instead of connecting to HTTPS you connect to HTTP, which will connect to nginx in the docker container, which will in turn connect to `example.com` over HTTPS, and the result will be returned to PHP over HTTP.

Royally over engineered, but at least it works :tada:

**Comment by DivineOmega** [comment]
I can confirm this is still an issue (tested with PHP 7.1).

**Comment by BanzaiMan** [comment]
Hello there. We've packaged PHP 7.2.8 (alias 7.2) and 7.1.18 (alias 7.1) with OpenSSL instead of GnuTLS. Some newer SSL/TLS protocols should now be usable. Please test them and report results.

Thanks.

**Comment by DivineOmega** [comment]
My testing shows this working in PHP 7.2, but not in PHP 7.1. 

Example build: https://travis-ci.org/DivineOmega/password_exposed/builds/385908542

**Comment by BanzaiMan** [comment]
Ah, 7.1 is pre-installed, so please try 7.1.18 instead. Thank you for the report!

**Comment by DivineOmega** [comment]
@BanzaiMan What do I need to put in my `.travis.yml` to try PHP 7.1.18?

**Comment by rpkamp** [comment]
```
php:
  - 7.1.18
```

**Comment by DivineOmega** [comment]
@rpkamp That should have been obvious to me really. Thank you. :+1: 

@BanzaiMan I can confirm 7.1.18 also works fine. Many thanks!

**Comment by zmike** [comment]
@BanzaiMan I just got this on all my Linux-based builds today https://travis-ci.org/Enlightenment/efl/builds/414295248

**Comment by MrPetovan** [comment]
I just got this issue, Travis Git can't retrieve a repository from a TLS 1.2-only SNI-enabled domain: https://travis-ci.org/friendica/friendica/jobs/434668926#L566

Full error:
```
[RuntimeException]                                                           
Failed to execute git clone --no-checkout 'https://git.friendi.ca/friendica/php-json-ld'
'/home/travis/build/friendica/friendica/vendor/friendica/json-ld'
&& cd '/home/travis/build/friendica/friendica/vendor/friendica/json-ld'
&& git remote add composer 'https://git.friendi.ca/friendica/php-json-ld'  
&& git fetch composer                                                       

Cloning into '/home/travis/build/friendica/friendica/vendor/friendica/json-ld'...                                                                       
fatal: unable to access 'https://git.friendi.ca/friendica/php-json-ld/': gnutls_handshake() failed: Handshake failed
```

SSLabs report: https://www.ssllabs.com/ssltest/analyze.html?d=git.friendi.ca&s=138.201.30.223

It still sounds like updating GNU TLS would fix the issue.

**Comment by afk11** [comment]
A project of ours encountered this issue a while back, around the time we moved our infrastructure. I only stumbled across this issue because I noticed curl was using gnutls, whereas my laptop was using openssl.

Testing against 7.1.18 did make the issue go away. I gave the c code a brief scan, and not 100% sure it's the issue, but I can't see it scanning the certificates directory like openssl does - just the certificates file.

**Comment by MrPetovan** [comment]
It appears the PHP CLI used by Travis to run Composer uses GNU TLS no matter the PHP version: https://travis-ci.org/friendica/friendica/builds/437234785

**Comment by mlwilkerson** [comment]
Update: I needed to get a test matrix working with some older php versions as well, but when specifying `5.6` in `.travis.yml`, or `7.0` I was just getting more php versions that failed on the GnuTLS thing. So I did some poking around and found that all of the following versions work. I have a nice, clean, green test matrix now:

(These first two were mentioned above)
- `7.2.6`
- `7.1.18`
(I dug around to find a couple more older ones)
- `7.0.32`
- `5.6.37`

So, I'm just specifying these in my `.travis.yml` like this:

```
matrix:
  include:
  - php: 7.2.6
    env: WP_VERSION=latest
  - php: 7.1.18
    env: WP_VERSION=latest
  - php: 7.0.32
    env: WP_VERSION=latest
  - php: 5.6.37
    env: WP_VERSION=4.4
  - php: 5.6.37
    env: WP_VERSION=latest
```

**Comment by louwie17** [comment]
Updating from `trusty` to `xenial` fixed this issue for me, as they contain newer minor version of php.
