### ISSUE TITLE
`dist: trusty` to build wrong Ubuntu version

### ISSUE THREAD

**Issue by jhen0409** [travis-ci/travis-ci#6372]
https://travis-ci.org/jhen0409/react-boilerplate/builds/147922980#L9-L17

The build 10 hours ago: Ubuntu 14.04.3 LTS

https://travis-ci.org/jhen0409/react-boilerplate/builds/148001231#L6-L14

Currently I get `Ubuntu 12.04.5 LTS` for using `dist: trusty`.

**Comment by BanzaiMan** [comment]
Sorry about the issue. We look into this shortly.

**Comment by BanzaiMan** [comment]
@jhen0409 Hello. We deployed a potential fix. Could you push a new commit to confirm? Thanks.

**Comment by michaelmior** [comment]
This is still failing for me

https://travis-ci.org/michaelmior/NoSE/jobs/148046803

**Comment by BanzaiMan** [comment]
@michaelmior That's a rerun of an old build. Please push a new commit.

**Comment by michaelmior** [comment]
@BanzaiMan Sorry, I assumed rerunning the build would have the same affect as pushing a new commit. I amended the commit and did a force push and the build is still failing

https://travis-ci.org/michaelmior/NoSE/jobs/148081788

**Comment by BanzaiMan** [comment]
@michaelmior We identified another issue. Could you push a new commit? Thank you!

**Comment by michaelmior** [comment]
@BanzaiMan Looks good now here! Thanks :)

**Comment by BanzaiMan** [comment]
@michaelmior Yay! Thanks for the confirmation. I'm closing this now!

**Comment by michaelmior** [comment]
@BanzaiMan Out of curiosity why does rerunning a build and starting a new build with the same code produce different behaviour?

**Comment by BanzaiMan** [comment]
@michaelmior The jobs is configured and routed to a build queue exactly once when we receive a build request. Re-running a job will not change this, so a new commit was necessary.

**Comment by jhen0409** [comment]
🔥 It works for me! Thanks! 👍

**Comment by sebix** [comment]
I can confirm the fix too :+1:
