### ISSUE TITLE
Matrix builds disabled for R?

### ISSUE THREAD

**Issue by rubak** [travis-ci/travis-ci#6385]
It seems like matrix builds are no longer supported for R. E.g. .travis.yml in jimhester/covr has

``` yaml
r:
  - oldrel
  - release
  - devel
```

And in [this build](https://travis-ci.org/jimhester/covr/builds/147803772) a few days ago the three versions were clearly run, but in [this build](https://travis-ci.org/jimhester/covr/builds/148034351) the next day only one version seems to run.
Any help to understand/resolve this will be appreciated.
cc: @craigcitro, @hadley and @jimhester

**Comment by BanzaiMan** [comment]
This is probably a bug on our side. We'll investigate next week. Sorry for the inconvenience.

**Comment by BanzaiMan** [comment]
This should be fixed now.

**Comment by imanuelcostigan** [comment]
Still fails

https://travis-ci.org/imanuelcostigan/aemo/jobs/153699047#L376
