### ISSUE TITLE
Android SDK Build-Tools 24.0.2 license problem

### ISSUE THREAD

**Issue by AlokBansal8** [travis-ci/travis-ci#6555]
* What went wrong:
A problem occurred configuring project ':lib-classes'.
> You have not accepted the license agreements of the following SDK components:

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by AlokBansal8** [comment]
Yeah. https://s3.amazonaws.com/archive.travis-ci.org/jobs/156619623/log.txt

**Comment by BanzaiMan** [comment]
It appears to have been fixed in https://travis-ci.org/AlokBansal8/UtilityClasses/builds/157195324.

**Comment by AlokBansal8** [comment]
Yeah. Adding the following lines to .travis.yml file helped:

````
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
````

But my doubt was that the CI should have automatically accepted all the licenses. And I should not have to resort to this step.

**Comment by stephengroat** [comment]
I'm having a similar issue (https://travis-ci.org/stephengroat/ics-openvpn) but `licenses` didn't seem to fix it

**Comment by httpdigest** [comment]
I'm also having this issue.
.travis.yml file and travis build log: https://gist.github.com/httpdigest/3a65fc9488b749037746ee2722abd81e

**Comment by houxg** [comment]
@httpdigest Actually the log already told you what happen:`Error: Ignoring unknown package filter 'build-tools-24.0.3'`. The travis's sdk version is out of date, you need to add `tools` to upgrade sdk itself first. For your example, like this:
```
components:
    - tools
    - build-tools-24.0.3
    - android-25
```

**Comment by httpdigest** [comment]
So, I take it that whenever one wants to use a newer build-tools version than what is already installed on the Travis CI build server, one needs to declare the `tools` component first? Or what is the purpose of the `tools` component; what does it do? I am asking because [this documentation](https://docs.travis-ci.com/user/languages/android/) is lacking an explicit statement of why one needs `tools` and what it does. There is just one comment:
```
# Uncomment the lines below if you want to
# use the latest revision of Android SDK Tools
```
But then after that, the `- build-tools-19.1.0` is added as well. So, does a project declaring both `tools` and `build-tools-19.1.0` use the "newest" build tools or the 19.1.0 version?

**Comment by houxg** [comment]
The Android SDK Tools installed on Travis server only fetching `https://dl-ssl.google.com/android/repository/repository-10.xml`(you can check the log), however the `Build-Tools 24.0.2` was in `https://dl-ssl.google.com/android/repository/repository-11.xml`.

yes I agree with you, the document should mention that what will happen if you don't use the latest revision of Android SDK Tools.

**Comment by GuillemRoca** [comment]
It may be the tools issue.

See this issue also for running on android-25: (https://github.com/travis-ci/docs-travis-ci-com/issues/779)

Example: 

```
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
```

**Comment by jaredsburrows** [comment]
Since this has not been fixed, just using command line:

```
install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-25.0.2
  - echo y | android update sdk -u -a -t android-25
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
```

**Comment by SailReal** [comment]
@jaredsburrows using command line is the only way it works for me, THANKS!

**Comment by danielpassos** [comment]
I have the same problem for `25.0.2`

**Comment by danielpassos** [comment]
I have fixed it adding a shell script file (`.travis-android-license-bugfix.sh`) with that content:

```shell
echo "$ANDROID_HOME"
mkdir "$ANDROID_HOME/licenses" || true
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
```

and calling it on my `.travis.yml`

```yaml
before_install:
  - bash .travis-android-license-bugfix.sh
```

**Comment by albodelu** [comment]
It's a good moment to migrate to sdkmanager and avdmanager, you can accept the license directly without workarounds as explained [here](http://stackoverflow.com/a/42736695/1009132):

      - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
      - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
