### ISSUE TITLE
Conditionally ignore some of the builds in a matrix

### ISSUE THREAD

**Issue by henrik242** [travis-ci/travis-ci#6685]
Given `.travis.yml`

    env:
      - matrix:
        - BAR=a
        - BAR=b
    script:
      - runbuild.sh

And `runbuild.sh`: 

    #!/usr/bin/env bash

    FOO=$(./someotherscript.sh)
    if [ "$FOO" = "$BAR" ]; then
      ./actually-do-build.sh
    else
      echo ignored
    fi

Now the "ignored" build will show up as successful.  I'd like for a way for it to show up as "ignored" or "not built" in the build matrix result view.  Is that possible?  

If not, this is a feature request :)

Maybe something like this?

    env:
      - matrix:
           - condition: ./shouldbuild.sh $BAR
           - BAR=a
           - BAR=b
    script:
      - ./actually-do-build.sh

**Comment by BanzaiMan** [comment]
The build matrix has to be configured before the build script can be compiled (let alone executed to evaluate conditions such as `if [ "$FOO" = "$BAR" ];`. As a result, we cannot implement this feature for use cases such as this.

It may be possible for other conditions, and we may consider them in the future.

For the time being, I am closing this.

**Comment by henrik242** [comment]
@BanzaiMan  OK. I guess the matrix has to be configured before reading the Git repo as well?  Because that's where the info I read is (I am looking for which paths have changed).

Another solution could be a special exit value from the script.  If exit == 101 then ignore build.  But I guess that's too hacky?

**Comment by BanzaiMan** [comment]
Right. The build matrix configuration must be derived from the information contained entirely in `.travis.yml`. Exit status is a bash construct that does not come into play in the build matrix configuration.

**Comment by henrik242** [comment]
@BanzaiMan   OK.  But some mechanism to tell travis to ignore this build result would be great.  Maybe something like setting TRAVIS_IGNORE_BUILD in the script phase?  This would make the build result show up as ignored (gray) instead of successful (green) or failed (red).

**Comment by henrik242** [comment]
This feature can partly be solved with issue #6301

**Comment by jgraham** [comment]
Is this something that can be solved now that build stages exist? What I would like is the ability to define an initial stage that inspects the list of files changed (or the commit message, or whatever) and then selects which entries from the build matrix should actually be scheduled. This is analogous to the way that the [decision task](https://docs.taskcluster.net/tutorial/gecko-decision-task) works on Mozilla's Taskcluster CI system. 

At the moment we are working around the lack of this feature in w3c/web-platform-tests by running the code to determine if a job should run in `before_install` and setting an environment variable which is checked in subsequent steps. This means that unwanted tasks still have to spin up a machine and do an initial git clone, which is rather wasteful of limited resources (the "skipped" tasks are shown as taking about 30s; idk how much hidden backend cost there is).

**Comment by BanzaiMan** [comment]
@jgraham Build Stages can be thought of as a Build Matrix with some special considerations as to how jobs are queued. It does not solve this problem.

We are hopeful to look into this feature request (#6301 and similar), but do not have ETA at this time.

**Comment by henrik242** [comment]
@BanzaiMan Any updates? :)

**Comment by henrik242** [comment]
@BanzaiMan @jgraham Any idea if this is possible to achieve now?

**Comment by BanzaiMan** [comment]
@henrik242 Sorry, but we have no updates.

**Comment by henrik242** [comment]
I guess a dynamically created matrix would solve this..
