### ISSUE TITLE
Container-based Trusty: pypy and pypy3 are not installed; attempting download

### ISSUE THREAD

**Issue by jwilk** [travis-ci/travis-ci#6865]
pypy3 builds in container-based Trusty fail with:
```
pypy3 is not installed; attempting download
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

The command "sudo tar xjf -.tar.bz2 --directory /" failed and exited with 2 during .
```

Full build log: https://travis-ci.org/jwilk/anorack/jobs/175361126

**Comment by flacjacket** [comment]
Just to bump this, I have the same problem with both pypy and pypy3 in the container trusty beta.

**Comment by BanzaiMan** [comment]
Hello. Does `pypy` work?

**Comment by BanzaiMan** [comment]
It does not. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/195343264

**Comment by asottile** [comment]
Here's a workaround we're using:

https://github.com/Yelp/venv-update/blob/19c18924afb55d23333150bf3bdb66da995b046f/.travis.yml#L12

**Comment by BanzaiMan** [comment]
Actually, I am thinking of reverting this. It is difficult to guess what version `pypy` should point to.

`pypy` and `pypy3` do not match up with `python`'s naming convention, and having to account for it is not a good idea.

**Comment by ssokolow** [comment]
I'd be happy with anything that lets me test "some reasonably recent PyPy and some reasonably recent PyPy3" in addition to the various CPython versions.

**Comment by asottile** [comment]
Even the cpython names aren't terribly well defined either.  travis-ci regularly upgrades patch versions which break cached virtualenvs (such as 3.6.0 -> 3.6.1)

At least for `pypy`, it's still going to target "python2.7" -- version updates there (at least in my mind) are akin to the same patch versions that happen all the time with cpython versions in travis-ci

**Comment by BanzaiMan** [comment]
I'm closing this. Due to the naming ambiguity. There will be other means of specifying PyPy versions consistently.

**Comment by asottile** [comment]
I'm not sure this should be closed, it's a clear regression from the precise images

**Comment by BanzaiMan** [comment]
`pypy` and `pypy3` are not names we can support consistently going forward.

Please use `pypy-x.y`.

**Comment by BanzaiMan** [comment]
We'll update the documentation shortly.

**Comment by asottile** [comment]
`python: 3.6` also isn't a consistent name to support either and the docs reflect **nothing** of this change (and this will break lots of builds)

**Comment by BanzaiMan** [comment]
It is true. But `3.6.0` is a consistent name with respect to the definitions in https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build, and we can infer `3.6` to mean "the latest MAJOR.MINOR" release of "3.6.x".

`pypy-x.y` is similar, but `pypy` is not.

**Comment by asottile** [comment]
Why can't `pypy` refer to the latest release of pypy?  Since all `pypy` target the "python 2.7 api" they're all _pretty_ compatible

**Comment by BanzaiMan** [comment]
Hmm. Maybe. I'll give it more thought. Thanks.

**Comment by riggsd** [comment]
Note that the Python support docs still refer to "pypy" and "pypy3":

https://docs.travis-ci.com/user/languages/python/#PyPy-Support

**Comment by wagner-certat** [comment]
Using `pypy-3.5` or `pypy3-3.5` also does not work for me, see:
https://travis-ci.org/wagner-certat/intelmq/jobs/254879791
https://travis-ci.org/wagner-certat/intelmq/jobs/254874949

Is there any known workaround to use pypy on trusty and sudo-enabled?

**Comment by drallensmith** [comment]
If this is at least partially a problem of version names, it would be nice for the error message to be more informative (as in detect it when parsing the .travis.yml file). And why the difference between linux (some succeed) and osx (none succeed)?

**Comment by Lyoness** [comment]
https://github.com/travis-ci/travis-cookbooks/pull/861

**Comment by drallensmith** [comment]
@BanzaiMan, I am seeing this error also on `precise` builds, albeit only with OS X. See [this build](https://travis-ci.org/drallensmith/neat-python/jobs/255642035).

**Comment by BanzaiMan** [comment]
@drallensmith We do not support Python on the Mac. https://github.com/travis-ci/travis-ci/issues/2312

**Comment by drallensmith** [comment]
Yes, I just found that out. It is very confusing that there's a system python on OSX builds, that can be used by python test scripts, but python as a build language may not be available.. when I'd be perfectly happy to just test vs the system python.

**Comment by drallensmith** [comment]
@BanzaiMan - well, now I'm seeing it on _precise_ builds on **linux** - see [here](https://travis-ci.org/drallensmith/neat-python/jobs/255772836).

**Comment by BanzaiMan** [comment]
@drallensmith Two things:

1. There is no `3.7` archive.
1. If you meant `3.7-dev`, it appears that there are build problems at the moment(e.g., https://travis-ci.org/travis-ci/cpython-builder/jobs/255309605).

I'll look into the latter issue shortly.

**Comment by BanzaiMan** [comment]
It appears that numpy is not yet 3.7-compatible, the build is failing.

**Comment by drallensmith** [comment]
Got it; thanks!

-Allen

**Comment by BanzaiMan** [comment]
`pypy` and `pypy3` should now work on all infrastructures. If you continue to see the problem, do let us know.

**Comment by asottile** [comment]
@BanzaiMan still seeing issues: https://travis-ci.org/pre-commit/pre-commit-hooks/jobs/257658233

**Comment by asottile** [comment]
(fwiw, I reported this earlier in #8081 but it was closed without fix)

**Comment by BanzaiMan** [comment]
The `pypy3` still does not work.

**Comment by asottile** [comment]
@BanzaiMan my link is `pypy` missing in the default `python` environment (it was present in the precise images -- this will likely break lots of python projects as they get upgraded)

**Comment by BanzaiMan** [comment]
@asottile Having `python: pypy` and `python: pypy3` is different from those runtimes pre-installed. `tox` requires pre-installation.

**Comment by asottile** [comment]
@BanzaiMan correct.  For `dist: precise`, both `pypy` and `pypy3` are preinstalled.  Neither are in `dist: trusty` which is a regression that will likely break **lots** of builds as they get automatically migrated to trusty.  This is what I was getting at in #8081

**Comment by BanzaiMan** [comment]
@asottile As I mentioned in #8081, we will continue that issue with #8160.

**Comment by asottile** [comment]
#8160 is a different issue.  Their configuration has `python: pypy3`: https://travis-ci.org/MartyMacGyver/DirTreeDigest/jobs/257614214/config

**Comment by BanzaiMan** [comment]
I've repackaged `pypy3.5-5.8.0` and `pypy2.7-5.8.0` archives, so that `python: pypy3` and `python: pypy` (respectively) work.

**Comment by BanzaiMan** [comment]
@asottile You're right about that. My apologies.

**Comment by asottile** [comment]
@BanzaiMan could you please *reopen* #8081 until it is fixed?

**Comment by KOLANICH** [comment]
There are problems wjth the following URIs:
```
https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/pypy3-nightly.tar.bz2
https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.11/x86_64/python-3.4.tar.bz2
https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.11/x86_64/python-3.5.tar.bz2
https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.11/x86_64/python-3.6.tar.bz2
https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.11/x86_64/pypy3.tar.bz2
https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.11/x86_64/pypy3-nightly.tar.bz2
```

**Comment by adamcharnock** [comment]
@BanzaiMan, it seems that the following URL is once again unavailable:

    https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
