### ISSUE TITLE
`sudo apt-get update` fails on GCE Trusty

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#6881]
We have received a few reports of `sudo apt-get update` failing due to TLS handshake error with apt.dockerproject.org. 

Affected repositories would have:

```yaml
sudo: required
dist: trusty
```
or
```yaml
sudo: required
services:
  - docker
```

The error would manifest in this way:

```
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

This is probably related to https://github.com/docker/docker/issues/16941. (Recent comments indicate that the Docker team is aware of the issue and is working with AWS to investigate further.)

We plan to add a temporary fix until the issue is resolved.

**Comment by BanzaiMan** [comment]
For those who want to fix it in their build *right now*, the one we are planning as a hot fix is what amounts to the following:

```yaml
before_install:
  - echo "54.230.142.136 apt.dockerproject.org" | sudo tee /etc/hosts
  ⋮ # rest
```

**Comment by BanzaiMan** [comment]
https://github.com/docker/docker/issues/28474 is the current issue on Docker.

**Comment by The-Compiler** [comment]
What about updating Travis-CI status in the meantime so people are aware of this?

**Comment by BanzaiMan** [comment]
@The-Compiler Thanks. We'll do that shortly.

**Comment by solarce** [comment]
We've opened a status incident to help inform people of the issue, https://www.traviscistatus.com/incidents/gmd6p074w061

**Comment by BanzaiMan** [comment]
Sorry, the fix earlier had a bad command. Instead of `| sudo tee`, you'd need `| sudo tee -a`. I fixed the comment above.

**Comment by webdevbyjoss** [comment]
zzzzzzz

**Comment by jonathansantilli** [comment]
@BanzaiMan Thanks but your workaround seems not to be working either :(

**Comment by BanzaiMan** [comment]
@jonathansantilli Oh, no! I'll take a deeper look.

**Comment by richelbilderbeek** [comment]
I can second that @BanzaiMan ! Here is the output of my build log:

![too_bad](https://cloud.githubusercontent.com/assets/2098230/20350534/961a54b6-ac0f-11e6-9f15-d78e7962727f.png)

Good luck!

**Comment by BanzaiMan** [comment]
Seems that switching off https in favor of http appears to be more reliable.

**Comment by BanzaiMan** [comment]
I spoke too soon. apt.dockerproject.org is not listening on port 80.

**Comment by jonnor** [comment]
I was affected by this from a "sudo apt-get install ..." line in `before_install`. Changing to use the Apt addon instead solved this case: https://github.com/imgflo/imgflo-server/commit/575337acc720cb4defc310c44019df445736bef8

Probably will not help with the case of actually installing Docker.

**Comment by BanzaiMan** [comment]
We are going to disable the Docker repository for now, until we can resolve the issue.

This way, `sudo apt-get install` would work, as long as the packages do not come from apt.dockerproject.org.

Thanks for your understanding.

**Comment by justinjdickow** [comment]
I can only assume that you are to blame for: https://status.github.com

**Comment by justinjdickow** [comment]
I can only assume that you are to blame for: https://status.github.com

**Comment by thaJeztah** [comment]
Just got informed that AWS identified a possible cause and is rolling out updates. It may take some time for those to be available everywhere. Hopefully the issue will be resolved by that.

**Comment by BanzaiMan** [comment]
@thaJeztah Thank you for the update and for keeping us in the loop.

**Comment by BanzaiMan** [comment]
Hi, everyone.

We've deployed a fix to remove the APT source for apt.dockerproject.org to production. `apt-get` commands should work now.

Please let us know if you continue to see problems.

Thank you for your patience.

**Comment by tobiaskley** [comment]
Hi, I still see an [error](https://travis-ci.org/tobiaskley/forecastSNSTS/jobs/176383377), but I am not certain if it is related. It sounds similar. Thanks for considering this and best regards, Tobias.

**Comment by trosendal** [comment]
Me too:
https://api.travis-ci.org/jobs/176393653/log.txt?deansi=true

**Comment by BanzaiMan** [comment]
@tobiaskley Yours is related, but slightly different, because the issue lies with an r-project.org source. This is tracked separately with #6882.

**Comment by mingp** [comment]
We continue to encounter this issue in one of our projects, now occurring with a different APT source. This is trying to install NodeJS from the NodeSource repos.

```
Step 2 : RUN curl -sL https://deb.nodesource.com/setup_4.x | bash -
 ---> Running in ad0e31b95c0c
## Installing the NodeSource Node.js v4.x LTS Argon repo...
## Populating apt-get cache...
+ apt-get update
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:3 http://deb.debian.org jessie Release.gpg [2373 B]
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [408 kB]
Get:5 http://deb.debian.org jessie Release [148 kB]
Get:6 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:7 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 9848 kB in 2s (3727 kB/s)
Reading package lists...
## Installing packages required for setup: apt-transport-https lsb-release...
+ apt-get install -y apt-transport-https lsb-release > /dev/null 2>&1
## Confirming "jessie" is supported...
+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_4.x/dists/jessie/Release'
## Adding the NodeSource signing key to your keyring...
+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK
## Creating apt sources list file for the NodeSource Node.js v4.x LTS Argon repo...
+ echo 'deb https://deb.nodesource.com/node_4.x jessie main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_4.x jessie main' >> /etc/apt/sources.list.d/nodesource.list
## Running `apt-get update` for you...
+ apt-get update
Ign https://deb.nodesource.com jessie InRelease
Hit http://security.debian.org jessie/updates InRelease
Ign https://deb.nodesource.com jessie Release.gpg
Ign https://deb.nodesource.com jessie Release
Ign http://deb.debian.org jessie InRelease
Hit http://deb.debian.org jessie-updates InRelease
Get:1 http://security.debian.org jessie/updates/main amd64 Packages [408 kB]
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:2 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Err https://deb.nodesource.com jessie/main Sources
  gnutls_handshake() failed: Handshake failed
Err https://deb.nodesource.com jessie/main amd64 Packages
  gnutls_handshake() failed: Handshake failed
Get:3 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
W: Failed to fetch https://deb.nodesource.com/node_4.x/dists/jessie/main/source/Sources  gnutls_handshake() failed: Handshake failed
W: Failed to fetch https://deb.nodesource.com/node_4.x/dists/jessie/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed
```

**Comment by solarce** [comment]
@tobiaskley @trosendal that is `Failed to fetch https://cloud.r-project.org/bin/linux/ubuntu/precise/Sources  gnutls_handshake() failed: A TLS fatal alert has been received.` which is due to cloud.r-project.org also being hosted on AWS CloudFront.

Ultimately the issue is with the CDN provider and we're waiting on them to fix the issue for everyone

**Comment by thaJeztah** [comment]
@mingp same issue for nodesource.com they are tracking this in https://github.com/nodesource/distributions/issues/388

**Comment by solarce** [comment]
@mingp that is `Err https://deb.nodesource.com jessie/main Sources  gnutls_handshake() failed: Handshake failed` which is due to deb.nodesource.com also being hosted on AWS CloudFront.

Ultimately the issue is with the CDN provider and we're waiting on them to fix the issue for everyone

**Comment by mingp** [comment]
@thaJeztah @solarce Thank you for the clarification. We'll go follow the other issue.

**Comment by tobiaskley** [comment]
@BanzaiMan @solarce thank you for explaining it so very well to me. If I understand correctly, there is nothing I can do about it now? Best, Tobias.

**Comment by BanzaiMan** [comment]
@tobiaskley Not very much, unfortunately. You might want to alert r-project.org maintainers to the issue, if you wish.

**Comment by eddelbuettel** [comment]
For what it is worth my Rcpp build on Travis now succeeded.  Yay.  

I use a [personal variant of the 'older' R Travis setup](http://eddelbuettel.github.io/r-travis/) using explicit `apt-get` calls to Ubuntu, CRAN, launchpad, ....   All fine now.  Thanks all!

**Comment by shouze** [comment]
@BanzaiMan ok looks like it's been fixed for docker, would you please revert your patch please?

**Comment by solarce** [comment]
@shouze Hiro is working on deploying that https://github.com/travis-ci/travis-build/pull/892

**Comment by BanzaiMan** [comment]
Hi, everyone. apt.dockerproject.org has been restored with https://github.com/travis-ci/travis-build/pull/892.

This has been deployed to production.

Let us know if you continue to have problems.

Again, thank you for your patience.

**Comment by BanzaiMan** [comment]
I should've asked the opposite. Let us know if you no longer see the problem. (So that we can close this issue!)

**Comment by shouze** [comment]
It's working perfectly on an in progress build with 10 jobs, all the 10 jobs have successfully installed docker 1.12.3! ;)

**Comment by BanzaiMan** [comment]
@shouze Thanks for the confirmation. I'm closing this now.

**Comment by puolukkamaenpuu** [comment]
bank

**Comment by puolukkamaenpuu** [comment]
ready

**Comment by puolukkamaenpuu** [comment]
[puolukkamaenpuu@gmail.com-Subscription-Activity-Oct-30,-2016-Nov-29,-2016.pdf](https://github.com/travis-ci/travis-ci/files/620207/puolukkamaenpuu.gmail.com-Subscription-Activity-Oct-30.-2016-Nov-29.-2016.pdf)

**Comment by The-Compiler** [comment]
@puolukkamaenpuu ...huh?
