### ISSUE TITLE
Weird log corruption

### ISSUE THREAD

**Issue by o11c** [travis-ci/travis-ci#7605]
Something *really* weird happened in one of my builds. It ran just fine, but the output is duplicated and interspersed, including in fully-travis-controlled sections.

The bad log is: https://travis-ci.org/o11c/python-uni/jobs/221184317

It didn't happen to any other logs in the same build, or in the prior or subsequent builds. So it's not a problem for *me*. But you might want to investigate what's wrong with your infrastructure.

**Comment by ivailop** [comment]
We experienced the same issue... It looks like 2 workers were started for the same job.

**Comment by BanzaiMan** [comment]
There was a race condition which may have led to multiple VMs getting started. We deployed a fix for this yesterday. Could you try restarting affected jobs?

**Comment by mpgo13** [comment]
We experienced the same issue on https://travis-ci.com a few hours ago:

The step `Setting environment variables from repository settings` can be found 6 times in the log!

**Comment by carlwright4** [comment]
(#7605)

**Comment by MariadeAnton** [comment]
This issue should be fixed now. If you run into this again, please drop us a line at [support@travis-ci.com](mailto:support@travis-ci.com). 

Thanks everyone!

**Comment by ivailop** [comment]
The issue is still happening - there are 2 workers started at https://travis-ci.org/testspace-samples/php.phpunit/builds/341986420
