### ISSUE TITLE
Error getting repository settings

### ISSUE THREAD

**Issue by Bohdankm22** [travis-ci/travis-ci#7831]
STR:

1. Add repository
2. Make a build (in my case it was failed)
3. Add an env variable
4. Rebuild the failed build
5. Go to Settings

Result: Message is displayed instead of the page with settings "There was an error while loading data."

I checked the issue in Safari and Google Chrome.

Here is an issue from the Chrome console log:
```
ember.prod.js:27546 Error while processing route: settings.index Cannot read property 'name' of null TypeError: Cannot read property 'name' of null
    at https://cdn.travis-ci.org/assets/travis-45454cdc389492d1a19339dd6d2e357c.js:5:3083
    at Array.reduce (native)
    at i._convertV3SettingsToV2 (https://cdn.travis-ci.org/assets/travis-45454cdc389492d1a19339dd6d2e357c.js:5:3052)
    at https://cdn.travis-ci.org/assets/travis-45454cdc389492d1a19339dd6d2e357c.js:5:2805
    at E (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:22:484)
    at P (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:22:598)
    at k (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:22:387)
    at invokeWithOnError (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:5:27614)
    at s.flush (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:5:28070)
    at u.flush (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:5:28832)
    at c.end (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:5:29177)
    at https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:5:26419
    at r (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:22:22761)
```

**Comment by coryan** [comment]
Same here, for an existing repository.

1. Open repository settings (earlier today)
2. Add an env variable
3. Go to Settings

Same results as above.  No problems opening Settings for old repositories.

**Comment by mendhak** [comment]
Similar, just got this problem:

    [Report Only] Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1…gpKTsKCQkJfQoJCX0KCX0pKCk7Cgl3aW5kb3cuX2dhcSA9IGdhcS5xZiA9IGdhcTsKfSkoKTs=' because it violates the following Content Security Policy directive: "script-src 'self' https://ssl.google-analytics.com https://djtflbt20bdde.cloudfront.net/ https://js.pusher.com https://cdn.travis-ci.org".

    ember.prod.js:27546 Error while processing route: settings.index Cannot read property 'name' of null TypeError: Cannot read property 'name' of null
        at https://cdn.travis-ci.org/assets/travis-45454cdc389492d1a19339dd6d2e357c.js:5:3083
        at Array.reduce (native)
        at i._convertV3SettingsToV2 (https://cdn.travis-ci.org/assets/travis-45454cdc389492d1a19339dd6d2e357c.js:5:3052)
        at https://cdn.travis-ci.org/assets/travis-45454cdc389492d1a19339dd6d2e357c.js:5:2805
        at E (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:22:484)
        at P (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:22:598)
        at k (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:22:387)
        at invokeWithOnError (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:5:27614)
        at s.flush (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:5:28070)
        at u.flush (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:5:28832)
        at c.end (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:5:29177)
        at https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:5:26419
        at r (https://cdn.travis-ci.org/assets/vendor-b2f9997f16f95d342211de957d84d386.js:22:22761)
    p @ ember.prod.js:27546
    error @ ember.prod.js:27487
    v @ ember.prod.js:27644
    c @ ember.prod.js:53076
    trigger @ ember.prod.js:53618
    (anonymous) @ ember.prod.js:53426
    E @ ember.prod.js:55688
    P @ ember.prod.js:55703
    k @ ember.prod.js:55671
    _ @ ember.prod.js:55606
    invokeWithOnError @ ember.prod.js:333
    flush @ ember.prod.js:394
    flush @ ember.prod.js:518
    end @ ember.prod.js:588
    (anonymous) @ ember.prod.js:1154
    r @ raven.js:377

**Comment by Princu7** [comment]
Can confirm the issue. Did the exact same steps and landed into the exact same problem.

**Comment by BanzaiMan** [comment]
Thanks for the reports, everyone. We are sorry for the inconvenience. We are looking at it now.

**Comment by BanzaiMan** [comment]
Hi, everyone.

We deployed a fix to prevent future occurrences of this issue, but issues may remain on some repositories. If you are having problems, please send us email at support@travis-ci.com, so that we can fix it for you. Please be sure to include the names of the affected repositories, and whether they are public or private.

Again, we apologize for the inconvenience, and thank you for your patience.

**Comment by Princu7** [comment]
@BanzaiMan Thanks for the support. Unfortunately, the issue is still not fixed in our repository. I have sent an email to the support staff. Hope it gets resolved soon. Thanks for building such an amazing platform.

**Comment by cotsog** [comment]
It might be possible to fix this yourself by using our CLI tool: https://github.com/travis-ci/travis.rb.

Can someone try the following recipe?

1) Run the following command:

```bash
$ cd path/to/repo/on/your/pc
$ travis settings builds_only_with_travis_yml
```

Here's the sample output you will see:

```bash
$ travis settings builds_only_with_travis_yml
Settings for cotsog/travis_ci_prod_regular:
[+] builds_only_with_travis_yml    Only run builds with a .travis.yml
```

2a) If you see a `+` (plus sign) between the square brackets (`[ ]`) on the left, run the following commands:

```bash
$ travis settings builds_only_with_travis_yml --disable
$ travis settings builds_only_with_travis_yml --enable
```

OR

2b) If you see a `-` (minus sign) between the square brackets (`[ ]`) on the left, run the following commands:

```bash
$ travis settings builds_only_with_travis_yml --enable
$ travis settings builds_only_with_travis_yml --disable
```

Please try this out and let us know if you can access your repo settings after doing 2a or 2b.

Thank you!

**Comment by ryansully** [comment]
The CLI fix wasn't successful for me. (YMMV)
Email sent.

**Comment by mendhak** [comment]
Hey Ryan I had to git reset to get it to work for me, did you try it in a
clean repository?

**Comment by ryansully** [comment]
I didn't try that, sorry. It was fixed by support. (Thanks again for such a quick response!)

**Comment by mohanagy** [comment]
Same here , the CLI fix wasn't successful :(

**Comment by MariadeAnton** [comment]
If you run into this issue again, please drop us a line at [support@travis-ci.com](mailto:support@travis-ci.com?Subject=Error%20viewing%20settings%20page%20#7831) with the full name of your repositories "OWNER_NAME/REPO_NAME". We'd be there to help.

Thank you all for your understanding!

**Comment by Juanlu001** [comment]
The CLI trick worked for me! :+1:

**Comment by tomfrenzel** [comment]
Worked for me too!!
