### ISSUE TITLE
Python regressed from 2.7.13 to 2.7.6

### ISSUE THREAD

**Issue by ctz** [travis-ci/travis-ci#8097]
Compare:

1. https://travis-ci.org/ctz/rustls/jobs/250169576#L1128 (older build which worked)
2. https://travis-ci.org/ctz/rustls/jobs/253983550#L1057 (recent build that failed, after 12th July update)
3. https://travis-ci.org/ctz/rustls/jobs/254002737#L1134 (same code as 2, just with `group: deprecated-2017Q3` set)

In the first, we're using Python 2.7.13. In the second, 2.7.6. Was that intended?

Thanks!

**Comment by BanzaiMan** [comment]
Do note that the builds use Rust.

**Comment by Lyoness** [comment]
Hello @ctz,  we've merged changes [here](https://github.com/travis-ci/travis-cookbooks/pull/871/files) that should fix this.  Currently they are available by specifying `group: edge` in your .travis.yml.  If you could try running a build with that, and let us know if that does the trick? 

We're looking to promote these `edge` images to stable soon.

**Comment by 13steinj** [comment]
In a similar boat here, but a slightly different issue. It's not a matter of the version of python changing between image versions, but rather that after the recent update, the python binaries are different between running python and running python as sudo (or running any process that calls python under sudo vs not). This is because `python` calls the 2.7.13 version from /opt, but `sudo python` calls the symlink to python2 from /usr/bin/python which pulls up 2.7.6. Because of this some libraries get installed for one version and not the other depending on whether or not `pip/python setup.py [develop|install]` was called with `sudo` (which some need to be in projects I maintain).

In .travis.yml I have
```
sudo: required
dist: trusty

language: python

python:
    - "2.7"

virtualenv:
    system_site_packages: true
```

in case it makes a difference between this issue and the one I'm having.

Specifying `group: edge` fixed the issue because (albeit through numerous symlinks through pyenv shims) both `python` and `sudo python` then call upon the same version (in my case, both 2.7.6).

I'm unaware if the set of changes referenced are what fixed my issue, but I can only assume so. For obvious reasons I'd much rather run on the stable group than edge, so I hope they're pushed to stable soon

**Comment by ctz** [comment]
> Hello @ctz, we've merged changes here that should fix this. 

Sorry, I missed this message. I've just tried `group: edge` and I still see that the python on $PATH is 2.7.6.

**Comment by Bouke** [comment]
I've also run into this. My builds start failing because python 2.7.6 errors out while getting packages from pypi: https://travis-ci.org/Bouke/SRP/jobs/276202690.

```
os:
  - osx
  - linux
language: generic
sudo: required
dist: trusty
osx_image: xcode9
before_install:
  - python -V
  - pip -V
```

**Comment by jonashaag** [comment]
This is still an issue, see https://travis-ci.org/robinhood/thorn/jobs/285587657 and https://github.com/jonashaag/thorn/blob/d5ec15349033ac3b3b040bdfac046503ace9aba0/.travis.yml

**Comment by sampsyo** [comment]
We're also seeing an old version of Python 2.7, despite specifying 2.7.13 in the config file:
https://travis-ci.org/beetbox/beets/jobs/294664392#L1109

**Comment by BanzaiMan** [comment]
@sampsyo That is not true.

In that commit, you've specified two jobs with 2.7.13 (https://travis-ci.org/beetbox/beets/jobs/294664391 and https://travis-ci.org/beetbox/beets/jobs/294664398). The one you're pointing to is https://github.com/beetbox/beets/blob/d64842ce5bf2ddec57078ca4d7345809b9693200/.travis.yml#L14-L15 (`2.7_with_system_site_packages`).

**Comment by sampsyo** [comment]
Oops! Thank you for pointing that out, @BanzaiMan.

**Comment by damieng** [comment]
@Lyoness Is the fix still only available on edge?
