### ISSUE TITLE
Failed to Fetch (Constant Issue)

### ISSUE THREAD

**Issue by mitchellkrogza** [travis-ci/travis-ci#8507]
This issue has been persisting for months now, even while we were still on Precise containers.

```
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: Failed to fetch https://packagecloud.io/basho/riak/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud.io port 443: Connection timed out
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/39x/InRelease  Unexpected type excepted 21 != 5
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud.io port 443: Connection timed out
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

HHVM team has discontinued support for Precise a while back, and we should not be allowing HHVM builds on Precise.

**Comment by mitchellkrogza** [comment]
Sure I can send you many as it happens almost daily and I am not using Precise, all my build containers are Trusty. I also don't use any PHP/HHVM on this project at all. 

https://travis-ci.org/mitchellkrogza/FUNCEBLE-Domain-List-Testing-Repo---001/builds/280345824

**Comment by BanzaiMan** [comment]
The issue was not very clear to me without the entire log. We'll take a look.

**Comment by mitchellkrogza** [comment]
@BanzaiMan let me know if you want to see logs from other projects where this behavior occurs

**Comment by mitchellkrogza** [comment]
@BanzaiMan here's another log where it happened again today > https://travis-ci.org/mitchellkrogza/Ultimate.Hosts.Blacklist/builds/280856953

**Comment by mitchellkrogza** [comment]
@BanzaiMan and here's another log from today > https://travis-ci.org/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects/builds/281329322

**Comment by BanzaiMan** [comment]
This seems to be a rather transient problem, no? https://travis-ci.org/BanzaiMan/travis_production_test/builds/284358915#L412-L414 did not show the problem just now.

**Comment by flimzy** [comment]
This is biting me as of today.
https://travis-ci.org/flimzy/kivik/jobs/289448081

**Comment by SkySkimmer** [comment]
Here's one https://travis-ci.org/SkySkimmer/coq/jobs/304499555
```
W: https://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)

W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)

W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out

W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Zimmi48** [comment]
BTW yes, this is a completely transient problem. But it's really annoying having to relaunch builds that fail for completely unrelated reasons.

**Comment by sskorol** [comment]
Noticed a similar issue today. Haven't seen it before.
https://api.travis-ci.org/jobs/309409976/log.txt?deansi=true

**Comment by Zimmi48** [comment]
This problem happens so much these days that it is completely destroying our workflow. We have to restart builds all the time.

**Comment by SkySkimmer** [comment]
Is everyone getting this issue using `addons: apt: ...` or does it ever happen with regular `apt-get` calls?

**Comment by BanzaiMan** [comment]
Is the failure happening on the same remote endpoint, or different ones?

**Comment by Zimmi48** [comment]
In our case, it's also `http://ppa.launchpad.net` or `https://packagecloud.io`.

**Comment by JasonGross** [comment]
It happens with manual `apt-get` calls too.  For example, https://travis-ci.org/mit-plv/fiat-crypto/jobs/327463402 fails because `apt-get update` fails with
```
$ sudo apt-get update -q
Ign:1 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty InRelease
Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates InRelease
Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports InRelease
Hit:4 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty Release
Ign:5 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
Get:6 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release [2,495 B]
Get:7 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release.gpg [801 B]
Ign:10 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:11 http://dl.google.com/linux/chrome/deb stable Release
Hit:12 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease
Ign:8 http://toolbelt.heroku.com/ubuntu ./ InRelease
Get:9 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Hit:13 http://security.ubuntu.com/ubuntu trusty-security InRelease
Hit:14 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease
Hit:15 http://toolbelt.heroku.com/ubuntu ./ Release
Hit:16 https://download.docker.com/linux/ubuntu trusty InRelease
Hit:18 https://dl.hhvm.com/ubuntu trusty InRelease
Ign:7 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release.gpg
Hit:19 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4/multiverse amd64 Packages
Ign:20 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Hit:21 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4/multiverse i386 Packages
Ign:21 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4/multiverse i386 Packages
Hit:21 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4/multiverse i386 Packages
Err:21 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4/multiverse i386 Packages
  Empty files can't be valid archives
Hit:23 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
Get:25 http://ppa.launchpad.net/jgross-h/many-coq-versions/ubuntu trusty InRelease [16.0 kB]
Hit:26 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
Hit:27 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
Hit:28 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease
Hit:29 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease
Hit:30 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
Hit:31 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty InRelease
Hit:32 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
Hit:33 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release
Get:35 http://ppa.launchpad.net/jgross-h/many-coq-versions/ubuntu trusty/main amd64 Packages [23.7 kB]
Get:36 http://ppa.launchpad.net/jgross-h/many-coq-versions/ubuntu trusty/main i386 Packages [23.7 kB]
Get:37 http://ppa.launchpad.net/jgross-h/many-coq-versions/ubuntu trusty/main Translation-en [6,404 B]
Fetched 76.2 kB in 2s (27.7 kB/s)
Reading package lists...
W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release: The following signatures were invalid: KEYEXPIRED 1515625755
W: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release' is not signed.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch store:/var/lib/apt/lists/partial/repo.mongodb.org_apt_ubuntu_dists_trusty_mongodb-org_3.4_multiverse_binary-i386_Packages  Empty files can't be valid archives
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update -q" failed and exited with 100 during .
```

**Comment by mitchellkrogza** [comment]
@JasonGross are Travis-CI container IP's not perhaps being blocked by Launchpad due to very high activity? Reason I ask is when containers do this I have tested from other locations and Launchpad is most definitely accessible 🤔

**Comment by kenorb** [comment]
Same [here](https://travis-ci.org/EA31337/FX-MT-VM/jobs/328262445) on new Trusty environment:

The first error in _Build system information_:

```
Executing: /tmp/tmp.mRWNwhpMw2/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv
0C49F3730359A14518585931BC711F9BA15703C6
gpg: requesting key A15703C6 from hkp server keyserver.ubuntu.com
gpg: key A15703C6: "MongoDB 3.4 Release Signing Key <packaging@mongodb.com>" 1 new signature
gpg: Total number processed: 1
gpg:         new signatures: 1
W: The repository 'http://dl.google.com/linux/chrome/deb stable Release' does not have a Release file.
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
127.0.0.1 localhost nettuno travis vagrant
127.0.1.1 travis-job-7e7fe520-e786-4145-a1fb-b4458bdbd351 travis-job-7e7fe520-e786-4145-a1fb-b4458bdbd351 ip4-loopback trusty64
```

Second error when running `apt-get update`:

```
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: The repository 'http://dl.google.com/linux/chrome/deb stable Release' is not signed.
E: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release.gpg  Connection failed [IP: 74.125.124.93 80]
E: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/main/binary-amd64/Packages  Connection failed [IP: 74.125.124.190 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

> This job ran on our Trusty environment, which has been updated on Tuesday, December 12th, 2017.

**Comment by carmat88** [comment]
Indeed, we are experiencing same kind of issues [here](https://travis-ci.org/kubenow/cron/jobs/326734003) on the new Trusty environment.

First error in _Build system information_ as reported by kenorb:

```
Build system information
...

Executing: /tmp/tmp.2wW3fuRvIp/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv
EA312927
gpg: requesting key EA312927 from hkp server keyserver.ubuntu.com
gpg: key EA312927: public key "MongoDB 3.2 Release Signing Key <packaging@mongodb.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
W: The repository 'http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release' does not have a Release file.
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/39x/InRelease  Could not connect to www.apache.org:80 (140.211.11.105), connection timed out
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud.io port 443: Connection timed out
W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out
W: Failed to fetch http://toolbelt.heroku.com/ubuntu/./InRelease  Unexpected type excepted 21 != 5
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
127.0.0.1 localhost nettuno travis vagrant
127.0.1.1 travis-job-14e70257-55d1-4da3-bafd-11e92420a02d travis-job-14e70257-55d1-4da3-bafd-11e92420a02d ip4-loopback trusty64
```

and then when trying to install few packages with apt-get:

```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install shellcheck jq python-pip
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libjq1 libonig4 python-pip-whl
Recommended packages:
  python-all-dev python-setuptools python-wheel
The following NEW packages will be installed:
  jq libjq1 libonig4 python-pip python-pip-whl shellcheck
0 upgraded, 6 newly installed, 0 to remove and 885 not upgraded.
Need to get 3,754 kB of archives.
After this operation, 18.8 MB of additional disk space will be used.
Get:1 http://ftp.us.debian.org/debian unstable/main amd64 libonig4 amd64 6.7.0-1 [153 kB]
Get:2 http://ftp.us.debian.org/debian unstable/main amd64 libjq1 amd64 1.5+dfsg-2 [123 kB]
Get:3 http://ftp.us.debian.org/debian unstable/main amd64 jq amd64 1.5+dfsg-2 [58.8 kB]
Get:4 http://ftp.us.debian.org/debian unstable/main amd64 python-pip-whl all 9.0.1-2 [1,406 kB]
Get:5 http://ftp.us.debian.org/debian unstable/main amd64 python-pip all 9.0.1-2 [179 kB]
Get:6 http://ftp.us.debian.org/debian unstable/main amd64 shellcheck amd64 0.4.6-1 [1,834 kB]
Fetched 3,754 kB in 0s (18.5 MB/s)
dpkg-deb: error: archive '/var/cache/apt/archives/libonig4_6.7.0-1_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/libonig4_6.7.0-1_amd64.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
Selecting previously unselected package libjq1:amd64.
(Reading database ... 93696 files and directories currently installed.)
Preparing to unpack .../libjq1_1.5+dfsg-2_amd64.deb ...
Unpacking libjq1:amd64 (1.5+dfsg-2) ...
Selecting previously unselected package jq.
Preparing to unpack .../jq_1.5+dfsg-2_amd64.deb ...
Unpacking jq (1.5+dfsg-2) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../python-pip-whl_9.0.1-2_all.deb ...
Unpacking python-pip-whl (9.0.1-2) ...
Selecting previously unselected package python-pip.
Preparing to unpack .../python-pip_9.0.1-2_all.deb ...
Unpacking python-pip (9.0.1-2) ...
Selecting previously unselected package shellcheck.
Preparing to unpack .../shellcheck_0.4.6-1_amd64.deb ...
Unpacking shellcheck (0.4.6-1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libonig4_6.7.0-1_amd64.deb
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Sub-process /usr/bin/dpkg returned an error code (1)
apt-get.diagnostics
apt-get install failed
$ cat ~/apt-get-update.log
Ign:1 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty InRelease
Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates InRelease
Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports InRelease
Hit:4 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty Release
Ign:5 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
Hit:6 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release
Ign:7 http://dl.google.com/linux/chrome/deb stable InRelease
Get:8 http://ftp.us.debian.org/debian unstable InRelease [240 kB]
Hit:10 http://dl.google.com/linux/chrome/deb stable Release
Get:9 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Hit:11 https://download.docker.com/linux/ubuntu trusty InRelease
Hit:13 https://dl.hhvm.com/ubuntu trusty InRelease
Get:15 http://ftp.us.debian.org/debian unstable/main amd64 Packages [10.5 MB]
Get:18 http://ftp.us.debian.org/debian unstable/main i386 Packages [10.5 MB]
Get:17 http://dl.bintray.com/apache/cassandra 39x/main amd64 Packages [682 B]
Get:19 http://dl.bintray.com/apache/cassandra 39x/main i386 Packages [682 B]
Get:20 http://ftp.us.debian.org/debian unstable/main Translation-en [5,943 kB]
Get:21 http://ftp.us.debian.org/debian unstable/contrib amd64 Packages [73.1 kB]
Get:22 http://ftp.us.debian.org/debian unstable/contrib i386 Packages [69.0 kB]
Get:23 http://ftp.us.debian.org/debian unstable/contrib Translation-en [51.3 kB]
Get:24 http://ftp.us.debian.org/debian unstable/non-free amd64 Packages [99.0 kB]
Get:25 http://ftp.us.debian.org/debian unstable/non-free i386 Packages [89.0 kB]
Get:26 http://ftp.us.debian.org/debian unstable/non-free Translation-en [84.0 kB]
Err:27 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
  Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out
Get:28 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease [23.2 kB]
Hit:29 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease
Get:30 https://packagecloud.io/github/git-lfs/ubuntu trusty/main Sources [20 B]
Get:31 https://packagecloud.io/github/git-lfs/ubuntu trusty/main amd64 Packages [5,930 B]
Get:32 https://packagecloud.io/github/git-lfs/ubuntu trusty/main i386 Packages [5,700 B]
Err:33 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:34 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:35 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:36 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:37 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:38 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Ign:39 http://toolbelt.heroku.com/ubuntu ./ InRelease
Get:40 http://toolbelt.heroku.com/ubuntu ./ Release [1,609 B]
Hit:41 http://security.ubuntu.com/ubuntu trusty-security InRelease
Get:42 http://toolbelt.heroku.com/ubuntu ./ Release.gpg [473 B]
Get:43 http://toolbelt.heroku.com/ubuntu ./ Packages [636 B]
Hit:44 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease
Fetched 27.7 MB in 20s (1,371 kB/s)
Reading package lists...
W: There is no public key available for the following key IDs:
7638D0442B90D010
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install shellcheck jq python-pip" failed and exited with 100 during .
```

Cheers.

**Comment by BanzaiMan** [comment]
@carmat88 That's https://github.com/travis-ci/travis-ci/issues/8823, is it not?

**Comment by smowton** [comment]
I've noticed some occasions where a couple of fetches fail early, but then the apt-get process as a whole still succeeds, which suggests WAN access became possible midway through the update/install process. Is it possible therefore that the container is racing against its network interfaces becoming usable? Would a simple while-can't-see-WAN-sleep-1 loop before starting to install packages help?

**Comment by tycho** [comment]
I just [ran into this as well](https://travis-ci.org/tycho/nbody/jobs/343273095). I'd bet Canonical is throttling Travis because of high activity. It could be solved by the Travis people hosting their own Ubuntu package mirrors -- this would work for everything but PPA repositories, since those aren't mirrored anywhere. But PPAs *are* Squid-cachable since they're using plain old HTTP for ppa.launchpad.net...

**Comment by jay** [comment]
+1 we've seen a number of these at random on the curl project, for example https://travis-ci.org/curl/curl/jobs/344678935

/cc @bagder

**Comment by jdpipe** [comment]
We're seeing this issue with another non-Launchpad package respository, openmodelica.org, details here:
https://www.openmodelica.org/download/download-linux
Is there some command I can add to simply confirm that my build has a live link to the outside world, eg by adding a 'ping' command or similar?

**Comment by JasonGross** [comment]
@jdpipe You can do something like `ping -c 5 8.8.8.8`, which tries to ping Google's public DNS server five times.  If you can't get through to 8.8.8.8, you probably can't get through to anything.

**Comment by jdpipe** [comment]
@JasonGross We added the ping thing to our .travis.yml, so it's there and running. But we haven't been seeing this bug with the Trusty build environment recently. Perhaps the networking issue has been solved, or perhaps the issue is sporadic and we've just struck it lucky recently...

**Comment by nathanross** [comment]
Just got this issue today, can confirm it's still happening.

**Comment by BanzaiMan** [comment]
@nathanross Thanks for the report. Do you have a build log URL to share?

**Comment by nathanross** [comment]
https://travis-ci.com/nathanross/sfdx-ci-demo/builds/69075420

**Comment by BanzaiMan** [comment]
I'm closing this issue in favor of #9112. I think it is the same issue, and would like to have information in one place.
