### ISSUE TITLE
Brew broken on OSX due to Ruby != 2.3

### ISSUE THREAD

**Issue by JustArchi** [travis-ci/travis-ci#8552]
https://travis-ci.org/JustArchi/ArchiSteamFarm/jobs/285211174#L537

This happened very recently, a few commits from like 20 minutes ago compiled properly. I did not change my travis configuration, neither anything setup-related.

Thank you in advance.

**Comment by leezer3** [comment]
+1
https://travis-ci.org/leezer3/OpenBVE/jobs/285218705

**Comment by JustArchi** [comment]
Yep, just for reference I reproduced it with both `xcode9` and `xcode9.1`. Don't want to dig deeper for no reason.

**Comment by Lectem** [comment]
Same issue here https://travis-ci.org/Lectem/cpp-boilerplate/jobs/285227989
I guess we could workaround by setting the ruby version ourself, but I don't like the idea of adding unrelated stuff to my .travis.yml

**Comment by MatthD** [comment]
Same here for me with xcode 8.3 asked on OSX travis.

**Comment by StrikerRUS** [comment]
+1

The same issue!

**Comment by joepvd** [comment]
As a workaround, could you try specify `export HOMEBREW_NO_AUTO_UPDATE=1` in your build configuration?

Thanks!

**Comment by Choc13** [comment]
+1

I am also having this issue [here[(https://travis-ci.org/wintoncode/Winton.AspNetCore.Seo/jobs/285459160) with a .NET Core C# build. It was working fine a couple of days ago, but today it has failed even though nothing in my travis build script has changed.

**Comment by JSkimming** [comment]
@joepvd I tried setting `export HOMEBREW_NO_AUTO_UPDATE=1`, see [here](https://travis-ci.org/JSkimming/Castle.Core.AsyncInterceptor/builds/285528226), but, at least as far as .NET Core builds are concerned, the homebrew update is executes before environment variables are set.

I ended up allowing OS X builds to fail as other's have chosen to do.

See JSkimming/Castle.Core.AsyncInterceptor#24.

**Comment by xoviat** [comment]
Is there a way to manually override the ruby version to one which hombrew supports?

**Comment by BanzaiMan** [comment]
Setting the environment variable in `.travis.yml` or the Settings panel should precede the C# runtime installation.

**Comment by JustArchi** [comment]
It does not. Neither on Linux nor OS X - **[this](https://travis-ci.org/JustArchi/ArchiSteamFarm/jobs/285215341#L489)** is happening as next step after installing .NET Core in my case.

**Comment by stephengroat** [comment]
a `brew update` before any `brew` commands will update the `brew` core and formula and fix the issue

**Comment by d99kris** [comment]
Thanks @stephengroat  - `brew update` solved the problem for me. https://travis-ci.org/d99kris/namp/jobs/285844547/config

**Comment by Zoramite** [comment]
I've tried to do a rvm command to `use 2.3.3` and did the `brew update` and that seems to have fixed the initial problems, but now I am having trouble [deploying build files](https://travis-ci.org/grow/grow/jobs/285882320) to github with this error message:

```
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.3.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.3'.
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.3.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.3'.
ERROR:  Could not find a valid gem 'dpl' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://api.rubygems.org/specs.4.8.gz)
The command "rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .
```

**Comment by stephengroat** [comment]
@BanzaiMan is there any schedule for when `brew` will be updated in the `osx` image?

**Comment by Choc13** [comment]
I have tried both `brew update` and `rvm use 2.3.3` in the `before_install` step of the OS X build, but neither of these work for me. I am building a .NET Core project and it looks like it automatically installs mono and then .NET Core before running the `before_install` script. It is during the .NET Core installation that I encounter the error `Homebrew must be run under Ruby 2.3!` as it is trying to do `brew install openssl`. See [here](https://travis-ci.org/wintoncode/Winton.AspNetCore.Seo/jobs/285936295) for an example.

Has anyone managed to work around this for .NET Core builds? Is there a way to change the version of ruby that is being used or update Homebrew before Travis tries to install .NET Core?

**Comment by slodki** [comment]
According to Travis [OS X build environment](https://docs.travis-ci.com/user/reference/osx/#Homebrew) documentation:

>Homebrew
>
>Homebrew is installed and updated every time the virtual machines are updated.
>
 >>  To speed up your build, try installing your packages without running brew update first, to see if the Homebrew database on the build image already has what you need.

not updated `brew` version is Travis bug.

**Comment by MatthD** [comment]
Brew update Works great for xcode 8.3 now I have:

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install fontconfig ; fi

**Comment by MariadeAnton** [comment]
Hi everyone!

This issue currently happens when using `os: osx`  together with any language that is not `language: objective-c`. 

When running `brew install package_name`, seems that brew tries to auto-update: 

```
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
==> Auto-updated Homebrew!
```

 effectively upgrading homebrew to `Homebrew 1.3.5` and reporting the following error: 

```
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': 
Homebrew must be run under Ruby 2.3! (RuntimeError)`
```

As suggested above, a possible workaround is running `brew update` right before `brew install package_name`. 

Running `brew update` before `brew install package_name` should work for all Travis CI Xcode images available but for `osx_image: xcode8.1`

We'll continue posting updates as we have them, thanks all!

**Comment by seesharper** [comment]
What is the workaround for us that installs the dotnet sdk like this?

```
language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode9      
      sudo: required      
      dotnet: 2.0.0    
before_install:
  - brew update
install:
  - ulimit -n4096  
script:  
  - dotnet test src/Dotnet.Script.Tests/Dotnet.Script.Tests.csproj
```

still outputs 

```
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! (RuntimeError)
```

**Comment by stephengroat** [comment]
@seesharper it seems like `travis` is using `brew` as part of it's process for `csharp` or `dotnet`.

one way would be to look at an old build, set the language to `generic`, and then manually set all of the required environment variables & install the required packages

**Comment by seesharper** [comment]
This information is for those of you that needs to install the dotnet sdk 

Instead of using `brew` to install the dotnet sdk, we can use an installation script provided by Microsoft.
https://github.com/dotnet/cli/blob/master/Documentation/specs/cli-installation-scenarios.md#installation-script

So here is the configuration we use now 
```
language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode9      
      sudo: required        
before_install:
  - brew update
  - curl https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
  - chmod +x dotnet-install.sh
  - ./dotnet-install.sh --channel 2.0
install:
  - ulimit -n4096  
script:  
  - ~/.dotnet/dotnet test src/Dotnet.Script.Tests/Dotnet.Script.Tests.csproj
```

**Comment by rok-povsic** [comment]
I was able to fix this error for .NET Core, see my answer [here](https://stackoverflow.com/questions/46670305/how-to-change-ruby-version-for-homebrew-in-macos-in-travis-ci/46756693#46756693).

**Comment by joeaudette** [comment]
@rok-povsic your answer on stackoverflow looks good except it looks like you are using .net core 1.x which is kind of old school by now. I wonder if the same script can work for 2.0 just by changing the --version, or is there a different 2.0 version of the script itself?

**Comment by rok-povsic** [comment]
@joeaudette Unfortunately I cannot test this as 2.0.0 has a bug with when using `dynamic`. They have fixed the bug but not released a new version yet. I've tried however to change the travis version to 2.0.0 and the build failed when detecting incompatible .NET core versions between the installed framework and the project. But since the error did not occur before that, I suspect the issue we talk about here wasn't encountered in the build

**Comment by kelson42** [comment]
Any chance to have a proper VM fix at some point? I wonder that this ticket is (still) not assigned to anybody!

**Comment by joeaudette** [comment]
@rok-povsic I can confirm that it does work for me using --version 2.0.0
Thanks for sharing your solution. I just need to go through and do the same with the rest of my projects now but it worked on the first one I tried.

**Comment by joeaudette** [comment]
@rok-povsic just noticed one strange thing, though it is building fine on both linux and osx, my tests only get run on linux, on osx it says:

Test run for /Users/travis/build/joeaudette/cloudscribe/test/cloudscribe.Core.Web.Test/bin/Release/netcoreapp2.0/cloudscribe.Core.Web.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
No test is available in /Users/travis/build/joeaudette/cloudscribe/test/cloudscribe.Core.Web.Test/bin/Release/netcoreapp2.0/cloudscribe.Core.Web.Test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

whereas on linux it finds and runs the tests:

Test run for /home/travis/build/joeaudette/cloudscribe/test/cloudscribe.Core.Web.Test/bin/Release/netcoreapp2.0/cloudscribe.Core.Web.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
[xUnit.net 00:00:00.9159021]   Discovering: cloudscribe.Core.Web.Test
[xUnit.net 00:00:01.0098634]   Discovered:  cloudscribe.Core.Web.Test
[xUnit.net 00:00:01.0169612]   Starting:    cloudscribe.Core.Web.Test
[xUnit.net 00:00:01.2506773]   Finished:    cloudscribe.Core.Web.Test
Total tests: 5. Passed: 5. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 3.9828 Seconds

To be honest though I don't know if the tests were being run before, possibly they never were running on osx, because failing to find the tests doesn't make the build result a failure.

This is happening for 2 different projects so far.

**Comment by rok-povsic** [comment]
@joeaudette Sorry, no idea. The tests run fine on both platforms for me.

**Comment by FGasper** [comment]
I received a related failure: `/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! (RuntimeError)`

https://travis-ci.org/FGasper/zmodemjs/jobs/288364117

**Comment by JustArchi** [comment]
Closing as this issue was solved in https://github.com/travis-ci/travis-build/pull/1229. Thank you @akoeplinger! 💓

**Comment by dcommander** [comment]
The comment above would imply that this fix was integrated into the Travis platform itself, but I'm still experiencing the issue with the xcode7.3 image.  Should that image have been fixed, or do I have to modify .travis.yml to work around the bug?  It would be nice to fix this in the image, since `brew update` takes some time and unnecessarily slows down the build (and adds unnecessary compute load to the servers.)

**Comment by StrikerRUS** [comment]
@dcommander The issue was solved only for C# language. For all other languages the fix will be released at 15th November with updated OSX images as it's said in the blog post.

**Comment by MatthiasWinkelmann** [comment]
Here's a pretty roundabout workaround that worked for me.  
```
os: osx
osx_image: xcode9.1
env:
  - HOMEBREW_DEVELOPER="Not really, but let's pretend I am until this travis bug gets fixed, ok?"
before_install:
  - rvm install "ruby-2.3.4"
  - export HOMEBREW_RUBY_PATH="/Users/travis/.rvm/rubies/ruby-2.3.4/bin/ruby"
  - rvm use 2.3
```

**Comment by fredrikaverpil** [comment]
> People that are not targetting C# explicitly will be probably solved with upcoming https://blog.travis-ci.com/2017-10-16-a-new-default-os-x-image-is-coming

Not sure if they new default images are in effect yet (they should be?) but I'm still getting "/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)":

Log: https://travis-ci.org/fredrikaverpil/pyside2-wheels/jobs/302883107

```
osx_image: xcode6.4
language: generic
```

**Comment by StrikerRUS** [comment]
@fredrikaverpil The same situation! I thought that they should change the default image yesterday, but nothing changed.

**Comment by JustArchi** [comment]
Alright, I'll open the issue for you then and let some Travis member close it once it's fixed 🙂

**Comment by dcommander** [comment]
I suppose the Nov. 15 date was a work of fiction?  Why isn't anyone from the Travis team updating us as to the status of this?  When can we expect new images?  There is nothing in the blog about why the deadline was missed.

**Comment by BanzaiMan** [comment]
The November 15 update has been postponed to November 28 (https://blog.travis-ci.com/2017-10-16-a-new-default-os-x-image-is-coming).

**Comment by mosra** [comment]
Two days ago, `brew install` was working properly on all my builds explicitly using the `xcode8.3` image. I switched from the at-the-time-default 7.3 as that fixed the Ruby error.

Today it's no longer case, running `brew install <something>` on the `xcode8.3` image fails *again* with the Ruby error, the same as it was previously on 7.3. In order to fix that, I have to:

- either explicitly call `brew update` before `brew install`, even though [it's recommended to not do that](https://docs.travis-ci.com/user/reference/osx/#Homebrew) and it adds *a minute and half* (!) to each of my macOS builds
- or *remove* the `osx_image: xcode8.3` from `.travis.yml` and use the default instead.

As far as I understood, the update was just flipping the default image from 7.3 to 8.3, the 8.3 image is unchanged since October and `osx_image: xcode8.3` is equivalent to just having the default. But that's apparently not the case. Can someone explain this behavior?

**Comment by yanntm** [comment]
Same here, builds are broken on 8.3 explicitly targetted image, worked fine before.

I'm using "brew update" as a workaround, but it's killing the penguins...

**Comment by heinrich5991** [comment]
```
if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
```

**Comment by StrikerRUS** [comment]
@mosra @yanntm I've faced the same issue yesterday. Nevertheless, at the present moment it's gone. Have you guys tried to restart your builds? Maybe Travis team is in progress and hasn't updated **all** their machines...

**Comment by yanntm** [comment]
The failure cropped up today : https://travis-ci.org/lip6/libITS/jobs/308921781/config
Working  run (last week) : https://travis-ci.org/lip6/libITS/jobs/306828363/config

Last build was 5 days ago, so I don't know when it started failing, but it's likely related to the updated infrastructure.

The strange part is that both runs claim to use the same xcode8.3 as @mosra explains in his post.

**Comment by mosra** [comment]
I have daily crons set up, so I know exactly when it started failing -- a build from 28.11. (roughly around noon UTC) was green, builds from this night and today are broken. And nope, nothing changed since, still failing even after restart.

**Also**, the `xcode7.3` image is *definitely not* Xcode 7.3 -- the LLVM version reported is 8.1, which is the same as in the default / `xcode8.3` image. It breaks my iOS 9 build. Is this maybe a related problem, all macOS images being somehow mixed up?

**Comment by yanntm** [comment]
Looking closer at the worker information, 
last week : Runtime kernel version: 16.7.0
This week : Runtime kernel version: 16.6.0

So the xcode8.3 image has regressed somehow.

**Comment by mosra** [comment]
Opened #8824 for the other possibly relevant image issue.

**Comment by dcommander** [comment]
I can confirm that the xcode7.3 image still exhibits the Ruby error.  Just tried it a few minutes ago.  So I guess Travis blew through another deadline.  Did I misunderstand that `brew update` was supposed to be added to xcode7.3 as well?  If not, then I guess I don't understand why this issue popped up in the first place.  I was successfully using xcode7.3 from December 1, 2016 until about a month ago, when this issue first surfaced.  This issue represents a regression in the xcode7.3 build image, and as such, it needs to be fixed.

**Comment by AraHaan** [comment]
Anyone here mind PRing my repo to make my OSX builds all allowed failures based on the ``kob-v2-and-v4-support`` branch?

https://github.com/Elskom/Els_kom_new
It seems that when I try making them as such they dont show up at all.

**Comment by AraHaan** [comment]
For me all versions of xcode has this problem when installing specific versions of gcc or clang.

**Comment by ThomasWaldmann** [comment]
xcode6.4 broken for us due to this. iirc, this worked until recently.

**Comment by ThomasWaldmann** [comment]
The brew-update workaround causes another issue btw (from travis failure log):
```
brew update
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
```
So, is travis-ci starting brew update and running it in the background?

**Comment by ThomasWaldmann** [comment]
considering that the OSX build farm is rather often at its capacity limits, maybe the travis team could look into solving this ticket.

it would also help reduce the load if developers do not have to run brew update in their travis scripts to work around the ruby version issue and not have to restart the build if that fails due to an already running brew update in the background causing a race condition.

so may i suggest:

- run brew update once and update the osx VM images to solve the ruby version issue
- do not run brew update in the background as it is causing this race condition
- notify people so they can remove brew update hack from their scripts again

**Comment by BanzaiMan** [comment]
I'm investigating this issue further. If you are still affected by it, please include the build log URL. Thanks.

**Comment by BanzaiMan** [comment]
It seems to me that `brew install` (https://travis-ci.org/BanzaiMan/travis_production_test/builds/339175377) as well as `brew update` (https://travis-ci.org/BanzaiMan/travis_production_test/jobs/339179699) are both working without further user input at this time.

As such, I'm closing this now. If you see problem to indicate otherwise, please include the build log URL, so that we can investigate further.

Thanks, everyone!

**Comment by ThomasWaldmann** [comment]
successful logs (with brew update in custom script):

- https://travis-ci.org/borgbackup/borg/jobs/337910044
- https://travis-ci.org/borgbackup/borg/jobs/337910045
