### ISSUE TITLE
macOS builds hanging after retrieving cache

### ISSUE THREAD

**Issue by relsqui** [travis-ci/travis-ci#8657]
Our macOS builds have been consistently hanging for the last 24 hours or so, using a Travis config file that hasn't changed in a few weeks. They seem to be stalling waiting for a password (?) after fetching the cache. Similar errors to the `shell_session_update` line below appear in old issues that have to do with certain macOS/Xcode version combinations, e.g. #6677, #6522, #6307, which makes me wonder if it's related to the [new osx image](https://blog.travis-ci.com/2017-10-16-a-new-default-os-x-image-is-coming) (even though that's not supposed to be out by default yet).

Example output:

```
Setting up build cache
/Users/travis/.travis/job_stages: line 1760: shell_session_update: command not found
$ export CASHER_DIR=$HOME/.casher
$ Installing caching utilities

attempting to download cache archive
fetching master/cache-osx-xcode7.3-025c65ec2e87c12f12f2fd644b492637f05954988432230d1174a6b09bb39e45--node-7.tgz
found cache

adding /Users/travis/.npm to cache
creating directory /Users/travis/.npm
Password:
```

**Comment by BanzaiMan** [comment]
Sorry about this issue. https://github.com/travis-ci/casher/pull/25 added `sudo` to the caching utility, so that the users can cache files not owned by `travis` (e.g., docker artifacts that the Docker daemon writes). This uncovered problems with recent Mac images where password-less `sudo` is not set up.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/builds/294117240 shows that the problem manifests on the Xcode 8.2 and later images.

**Comment by BanzaiMan** [comment]
I've updated the casher to not call `sudo -v` on the Mac, but it's not in production yet.

```yaml
cache:
  edge: true
  ⋮ # rest
```

If the current configuration is as simple as

```yaml
cache: bundler
```
more work is unfortunately necessary:

```yaml
cache:
  bundler: true
  edge: true
```

I plan to push this to production on Monday.

**Comment by relsqui** [comment]
Thanks @BanzaiMan! I'm in no more hurry than Monday--have a great weekend. :)

**Comment by ewanmellor** [comment]
@BanzaiMan The casher tests only run on Linux, and do not cover macOS.  Also, the current test runs print "could not download cache" and then exit with success, which seems kind of pointless.  I'm not sure what they are testing.  I think casher's test coverage needs expanding to stop these kinds of things reaching production.

**Comment by BanzaiMan** [comment]
I've pushed the fix, where Mac do not use `sudo` for `tar`. Please confirm that it is working for you.

Thank you.

**Comment by relsqui** [comment]
A previously-failing job is still failing, when I rebuild it, but I'm not sure if it's expected for it to pick up the fix retroactively. I'll keep an eye out for a new job to check (the last one went out right before you pushed the fix).

**Comment by ewanmellor** [comment]
@BanzaiMan This is still hanging for me too.  See https://travis-ci.org/ewanmellor/antlr4/jobs/294246884 for example.

**Comment by BanzaiMan** [comment]
Ooops. I forgot to restart a component, which is necessary for the new version to be effective. Sorry about that. Please try again.

**Comment by relsqui** [comment]
Looks good over here! Thanks!

**Comment by BanzaiMan** [comment]
Great. I'm closing this now.
