### ISSUE TITLE
Android: Platform tools v26.0.2 not installing

### ISSUE THREAD

**Issue by miankhalid** [travis-ci/travis-ci#8676]
On 26th October my builds suddenly started to fail and none of the mentioned workarounds are working for me (like https://github.com/travis-ci/travis-ci/issues/6193). The exact issue being reported in my lint report:

`The SDK platform-tools version (23.0.1) is too old to check APIs compiled with API 25; please update`

Here's the Travis job's log: https://api.travis-ci.org/jobs/294869249/log.txt?deansi=true

The link to my PR: https://github.com/edx/edx-app-android/pull/1020

`platform-tools revision 26.0.2` was recently released whose download is finishing with the wrong checksum, thus Travis is using the fallback `platform-tools revision 23.0.1` for running lint on my project causing the issue.

Here's the error excerpt from the job's log (https://api.travis-ci.org/jobs/294869249/log.txt?deansi=true):

```
Installing Archives:

  Preparing to install archives

  Downloading Android SDK Platform-tools, revision 26.0.2

  Download finished with wrong checksum. Expected b8130e7c390496cff12bf9355739bd41eed6a0a5, got 668ff8e319715175ff628ad52b124f154275fe2d.

  Done. Nothing was installed.
```

Any idea for a fix?

**Comment by miankhalid** [comment]
Here's my `travis.yml` file

```yml
language: android
jdk: oraclejdk8
sudo: required
dist: precise # For 7.5GB of memory since the emulator requires a big chunk.
env:
  matrix:
    - ANDROID_TARGET=android-25
  global:
    - ADB_INSTALL_TIMEOUT=12

android:
  components:
   - tools
   - tools
   - platform-tools
   # The BuildTools version used
   - build-tools-25.0.3
   # The SDK version used to compile the project
   - android-25
   # Additional components
   - extra-google-m2repository
   - extra-android-m2repository

notifications:
  email: true

before_script:
  - git fetch --tags
  - git fetch --unshallow || true
  - export DESCRIBE=$(git describe)
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, DESCRIBE=$DESCRIBE"
  - chmod +x gradlew
  # Begin spinning up an emulator in the background
  - make emulator

script:
  - make quality
#  - make test
  # Check if emulator has finished booting
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &
#  - travis_wait make e2e
  # Script to print lint information in logs.
  - ./gradlew lintProdDebug --info

after_script:
  - make artifacts
  - mv OpenEdXMobile/screenshots artifacts/
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - ~/bin/artifacts upload artifacts

branches:
  only:
    - /.*/

# Enable caching to speed up the build
cache:
  directories:
    - $HOME/.gradle

before_install:
  - pip install --user codecov
  - pip install --user pillow # For screenshot tests
  - mkdir "$ANDROID_HOME/licenses" || true

sudo: required
after_success:
  - codecov
  - if [ $TRAVIS_BRANCH == "master" ]; then
      pip install virtualenv;
      virtualenv ~/env;
      source ~/env/bin/activate;
      pip install transifex-client;
      sudo echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc;
      tx push --source --no-interactive;
      fi
```

**Comment by flavioarfaria** [comment]
This also affects me. I tried the workaround mentioned in https://github.com/travis-ci/travis-ci/issues/6699, but it doesn't help. It suddenly started complaining about it, since I haven't touched the `travis.yml` for a long time.

**Comment by flavioarfaria** [comment]
@miankhalid I've managed to get it fixed by declaring `dist: trusty` instead. I hope this helps you too.

**Comment by miankhalid** [comment]
@flavioarfaria Still failing. Other than the `platform-tools` not installing, sadly the emulator is also not working after this change.

**Comment by phansch** [comment]
We had the same problem in our Android build and changing `android-25` to `android-26` made the checksum issue go away. I'm not an Android developer, but I guess this only helps if you can upgrade to SDK version 26 without any problems.

**Comment by miankhalid** [comment]
@phansch Can you share your `travis.yml` file.

**Comment by flavioarfaria** [comment]
@miankhalid, I also had problems with the emulator and made a few changes to my travis file:

```yaml
language: android
sudo: required
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - extra-android-m2repository
    - android-26
    - extra-google-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - '.+'

jdk:
  - oraclejdk8

env:
  global:
    - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=1024m"

notifications:
  email: false

git:
  submodules: false

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - sdkmanager tools
  - sdkmanager "system-images;android-19;default;armeabi-v7a"

before_script:
  - echo no | avdmanager create avd --force -n test -k "system-images;android-19;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - ./scripts/test_android.sh
```

Using `$ANDROID_HOME/emulator/emulator` to start it was helpful.

**Comment by q88535448** [comment]
i have updated 26.0.1 then the 26.0.2 update is success

**Comment by GuilhE** [comment]
I'm also having this problem, never had before.

```
language: android
dist: trusty

android:
  components:
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - '.+'

jdk:
  - oraclejdk8

script:
  - ./gradlew build

before_install:
  - chmod +x gradlew

branches:
  only:
    - master

```

**Comment by GuilhE** [comment]
Fixed by changing **components** to:
```
components:
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.1
    - build-tools-26.0.2
    - android-26
    - extra-android-support
```

**Comment by miankhalid** [comment]
I didn't do anything and the issue seems to be fixed now 😆 

More details can be found here: https://github.com/edx/edx-app-android/pull/1020

**Comment by thusanka** [comment]
yes i am fix this on this article https://www.artsapi.lk
