### ISSUE TITLE
Not showing my repositories

### ISSUE THREAD

**Issue by yourWaifu** [travis-ci/travis-ci#8689]
Hello, new to Travis ci and for some reason I'm not getting my repositories. I keep clicking sync, but my repositories don't show up, instead, I get repositories that are locked and not mine.
![image](https://user-images.githubusercontent.com/16181109/32309293-0aced88a-bf61-11e7-8730-e97e3cdaf4ff.png)
I'm using Chrome Version 63.0.3239.30 (Official Build) beta (64-bit) on Windows.

All I do was authorize and nothing else.

I would love to be able to use Travis Ci, but this is stopping me from being able to do so.

**Comment by yourWaifu** [comment]
I found out that I can access my repositories by going directly to my repository via a URL. For example, https://travis-ci.org/yourWaifu/example.

I don't know if I should keep this open tho, it seems like this is a bug that should be fixed.

**Comment by solvingj** [comment]
I have some which are also locked, however going to the URL doesn't allow me to activate Travis on the repo.

**Comment by taystack** [comment]
This is not resolved yet. Can someone give me an explanation of why this public repo isn't listed in `travis-ci.org`?

---

This is my repo at https://github.com/taystack/js-big-list :

<img width="996" alt="screen shot 2019-01-30 at 5 43 36 pm" src="https://user-images.githubusercontent.com/2994672/52024740-bc1a5180-24b6-11e9-94c1-0711f7fbf714.png">

---

This is what https://travis-ci.org/taystack/js-big-list has:

<img width="684" alt="screen shot 2019-01-30 at 5 45 31 pm" src="https://user-images.githubusercontent.com/2994672/52024811-f257d100-24b6-11e9-813d-06787e399976.png">

---

I totally love the Travis-ci service, but this is lame. I just want a build badge...

**Comment by leonardoInf** [comment]
try syncing your repos and sometimes you'll just have to wait a little until travis-ci updates your repo list

**Comment by Crog** [comment]
I'm getting this same issue, is it confirmed we just need to wait. Somewhat odd as I had Travis Setup previously on the Repos which are not showing up anymore....

After fiddling though I can now access: https://travis-ci.com/Crog/Sub0Pub but get an odd migration message:
![image](https://user-images.githubusercontent.com/3353171/62329578-3e0f2580-b4ae-11e9-90e6-56aaa6d46043.png)

**Comment by hugomassing** [comment]
Also have this problem on a repo where it was working fine 2 hours before. When accessing with the URL, I have the same screen as @Crog.

**Comment by Crog** [comment]
I resolved my issue by going to travis-ci.org (not dot Com) and then selecting to join migration (didn't take pics sadly). Next day I could then chose to migrate the repos from org to con site 😊

**Comment by QueensCoder** [comment]
Re-syncing my account did the trick for me. The last sync was 21 minutes ago while my repo was created 20 minutes ago. Strangely enough, the repo showed on travis-ci.com without the re-sync

**Comment by yafp** [comment]
i had the same issue with a public repo on github which was not displayed on https://travis-ci.org.

**without effect**
* The repo already existed for several days
* Several re-syncs did not solve that issue.

**fix**
* What in fact did help was logging out and in again to https://travis-ci.org

**Comment by fepegar** [comment]
@yafp's solution worked for me: signing out and in.

**Comment by KEINOS** [comment]
@yafp's solution worked for me too: sign out then sign in with GitHub again

Thanks!

**Comment by isqo** [comment]
@yourWaifu and @yafp solutions didn't work for me, i had to change completely the browser i was using to get it work, may be it has to do with some caching done by travis server. btw, i also cleaned all the cached data of travis but din't change anything.
