### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by finspin** [travis-ci/travis-ci#9104]
My Docker builds started to suddenly fail with the following error:

```
docker build -t mydockerimage:0.0.1 .
Cannot connect to the Docker daemon at tcp://[secure]:2375. Is the docker daemon running?
```

Build log reports that docker daemon is running:

```
$ sudo service docker start
start: Job is already running: docker
```

My config:

```
{
  "sudo": false,
  "services": [
    "docker"
  ],
  "language": "generic",
  "install": [
    "pip install --user awscli"
  ],
  "script": [
    "docker build -t mydockerimage:0.0.1 .",
    "<more commands>"

  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
```

Anybody else experiencing problems?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by finspin** [comment]
Sorry, should have posted that right away https://travis-ci.org/finspin/testmeplease.site/builds/331253957

**Comment by BanzaiMan** [comment]
Looking at the build history, this appears to be the build that broke it. https://travis-ci.org/finspin/testmeplease.site/builds/331244504

**Comment by finspin** [comment]
I now reverted to the last working commit but the build is still failing with the same error https://travis-ci.org/finspin/testmeplease.site/builds/331950804

**Comment by BanzaiMan** [comment]
Thanks for testing. I'm not quite sure how the docker daemon could be not running here. We can enable the debug feature for this repo, if you'd like to try that.

**Comment by finspin** [comment]
Yes please, go ahead, let's try with the debug mode.

**Comment by BanzaiMan** [comment]
Done. See https://docs.travis-ci.com/user/running-build-in-debug-mode/ as well. Thanks.

**Comment by finspin** [comment]
I still don't see the Debug mode button. There is only the Restart build button.

**Comment by BanzaiMan** [comment]
@finspin The button does not appear for .org repos. Please read the document; it shows you how to send the API request to initiate a debug build.

**Comment by finspin** [comment]
OK, got it. It seems like there is something wrong with Docker daemon on the host but I don't know what. All Docker commands take very long to execute. For instance, `docker --version` takes about 30 seconds before it returns the response.

Trying to list all containers fails with the error:

```
travis@travis-job-bc2a3f8b-f9bb-4b8c-bf97-a7ad07e21e76:~/build/finspin/testmeplease.site$ ls
app.js  Dockerfile  package.json  public  README.md  VERSION  views
travis@travis-job-bc2a3f8b-f9bb-4b8c-bf97-a7ad07e21e76:~/build/finspin/testmeplease.site$ docker --version
Docker version 17.09.0-ce, build afdb6d4
travis@travis-job-bc2a3f8b-f9bb-4b8c-bf97-a7ad07e21e76:~/build/finspin/testmeplease.site$ docker ps -a
Cannot connect to the Docker daemon at tcp://35.162.16.197:2375. Is the docker daemon running?
travis@travis-job-bc2a3f8b-f9bb-4b8c-bf97-a7ad07e21e76:~/build/finspin/testmeplease.site$
```

I also tried restarting the docker service but it did not have any effect. VM disk size and CPU all look normal.

I'm not sure how to further debug this.

**Comment by finspin** [comment]
@BanzaiMan any pointers what else I could try? This is a showstopper for me. Should I instead use plain VM and install docker tools on it myself? What is the recommended practice for docker builds?

**Comment by BanzaiMan** [comment]
I'm sorry to say that I do not know why this is happening on your repository. I tried cloning your repository and ran `docker build`, and it was successful. https://travis-ci.org/BanzaiMan/travis_production_test/builds/334195463#L568

**Comment by finspin** [comment]
I noticed that in your config there is no mention of docker service. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/334195464/config

How come Docker is available in the build?

**Comment by BanzaiMan** [comment]
Because it uses Trusty with `sudo: required`.

**Comment by finspin** [comment]
Found the issue at last. I had defined environment variable called `DOCKER_HOST` which conflicted with Docker's variable of the same name. Phew.

**Comment by BanzaiMan** [comment]
Awesome!

**Comment by gillchristian** [comment]
Hi, I have the same issue but in my case I'm not using the `DOCKER_HOST` variable.

This is the build: https://travis-ci.com/github/gillchristian/tsplay.dev
