### ISSUE TITLE
Builds failing: Unable to connect to ppa.launchpad.net:http (apt-get install failed) (redis-server)

### ISSUE THREAD

**Issue by WaleedAshraf** [travis-ci/travis-ci#9112]
We are facing this issue for almost 2 weeks on multiple builds. I sent a mail to support@travis-ci last week, but there is still no reply. I saw some issue here with similar type but not sure if they are related.

```
travis_time:end:156b8175:start=1516612466767988891,finish=1516612467123820143,duration=355831252
[0Ktravis_fold:start:apt-get.diagnostics
[0K[31;1mapt-get install failed[0m
$ cat ~/apt-get-update.log
Hit:1 http://apt.postgresql.org/pub/repos/apt precise-pgdg InRelease
Ign:2 http://downloads-distro.mongodb.org/repo/debian-sysvinit dist InRelease
Hit:3 http://security.ubuntu.com/ubuntu precise-security InRelease
Get:4 http://downloads-distro.mongodb.org/repo/debian-sysvinit dist Release [2,040 B]
Get:5 http://downloads-distro.mongodb.org/repo/debian-sysvinit dist Release.gpg [490 B]
Get:6 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise InRelease [13.3 kB]
Get:7 http://downloads-distro.mongodb.org/repo/debian-sysvinit dist/10gen amd64 Packages [30.9 kB]
Get:8 http://downloads-distro.mongodb.org/repo/debian-sysvinit dist/10gen i386 Packages [30.5 kB]
Err:9 https://packagecloud.io/computology/apt-backport/ubuntu precise InRelease
  Failed to connect to 2607:f0d0:2101:270::2: Network is unreachable
Ign:10 http://us-central1.gce.archive.ubuntu.com/ubuntu precise InRelease
Hit:11 http://us-central1.gce.archive.ubuntu.com/ubuntu precise-updates InRelease
Hit:12 http://us-central1.gce.archive.ubuntu.com/ubuntu precise-backports InRelease
Hit:13 http://us-central1.gce.archive.ubuntu.com/ubuntu precise Release
Err:15 http://ppa.launchpad.net/couchdb/stable/ubuntu precise InRelease
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:16 http://ppa.launchpad.net/git-core/v1.8/ubuntu precise InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:17 http://ppa.launchpad.net/pollinate/ppa/ubuntu precise InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:18 http://ppa.launchpad.net/travis-ci/zero-mq/ubuntu precise InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:19 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:20 http://ppa.launchpad.net/ubuntugis/ppa/ubuntu precise InRelease
  Unable to connect to ppa.launchpad.net:http:
Err:21 http://ppa.launchpad.net/webupd8team/java/ubuntu precise InRelease
  Unable to connect to ppa.launchpad.net:http:
Ign:22 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise/main amd64 Packages
Ign:23 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise/main i386 Packages
Ign:24 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise/main Translation-en
Ign:22 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise/main amd64 Packages
Ign:23 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise/main i386 Packages
Ign:24 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise/main Translation-en
Err:22 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise/main amd64 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:23 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise/main i386 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:24 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise/main Translation-en
  Unable to connect to ppa.launchpad.net:http:
Fetched 77.3 kB in 10s (7,559 B/s)
Reading package lists...
W: http://security.ubuntu.com/ubuntu/dists/precise-security/InRelease: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
W: http://downloads-distro.mongodb.org/repo/debian-sysvinit/dists/dist/Release.gpg: Signature by key 492EAFE8CD016A07919F1D2B9ECBEC467F0CEB10 uses weak digest algorithm (SHA1)
W: http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/precise-updates/InRelease: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
W: http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/precise-backports/InRelease: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
W: http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/precise/Release.gpg: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/precise/InRelease  Failed to connect to 2607:f0d0:2101:270::2: Network is unreachable
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/precise/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/git-core/v1.8/ubuntu/dists/precise/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/precise/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/travis-ci/zero-mq/ubuntu/dists/precise/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/precise/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/ubuntugis/ppa/ubuntu/dists/precise/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/precise/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/precise/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/precise/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/precise/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
travis_fold:end:apt-get.diagnostics
[0K
[31;1mThe command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install g++-4.8" failed and exited with 100 during .[0m

Your build has been stopped.
```
We are using Travis Premium.

**Comment by BanzaiMan** [comment]
https://answers.launchpad.net/launchpad/+question/663396

We will respond to your support ticket shortly.

**Comment by halorium** [comment]
I believe I am experiencing a similar issue

**Comment by pitrou** [comment]
We've been seeing this on multiple builds as well. It's quite painful. Example: https://travis-ci.org/apache/arrow/jobs/335088022

**Comment by pitrou** [comment]
By the way, it's not only ppa.launchpad.net, so perhaps it's a connectivity issue on the Travis-CI side:
```
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://toolbelt.heroku.com/ubuntu/./Release.gpg  Unable to connect to heroku-toolbelt.s3.amazonaws.com:http:
```

**Comment by pitrou** [comment]
Also:
```
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud.io port 443: Connection timed out
```
(from https://travis-ci.org/apache/arrow/jobs/335088024)

**Comment by WaleedAshraf** [comment]
@pitrou We are also STILL facing this issue. I also added details on [launchpad](https://answers.launchpad.net/launchpad/+question/663396) ticket @BanzaiMan mentioned above. But there is still no response from Travis team. 😞

**Comment by dbudwin** [comment]
I am also experiencing this same issue.  It has been going on for a while:

```
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/39x/InRelease  Could not connect to www.apache.org:80 (140.211.11.105), connection timed out
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

See: https://travis-ci.org/dbudwin/RoboHome-Web/jobs/335442485#L416

**Comment by pitrou** [comment]
@BanzaiMan any news on this? It's not only `ppa.launchpad.net` that's having problems (see above).

**Comment by pevik** [comment]
@BanzaiMan This issue should be reopened. We have problems not only to ppa.launchpad.net https://travis-ci.org/linux-test-project/ltp as well. I keep restarting it, but these false positives are bad :-(.

**Comment by soulshake** [comment]
For all who are experiencing timeouts during `apt-get` commands, answers to the following questions would be useful:

1. [Which infrastructure(s)](https://docs.travis-ci.com/user/reference/overview/#For-a-finished-build) are you experiencing this on (`ec2`, `gce`, `jupiter`)?
2. Can you pinpoint when it started happening?
3. At which point in your `.travis.yml` does this fail (`before_install`, `script`, `addons.apt.packages`, etc)?
4. Roughly how often does this occur (e.g. "1 in 10 jobs")
5. Have you found a reliable workaround?
6. Have you found a way to reliably reproduce?
7. When it occurs, does it always cause the job to fail, or does the job succeed despite the error (or a mix of both)?

Feel free to include the full line containing the error you receive (e.g. `W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out`) and links to jobs encountering this issue to help us track this down.

**Comment by soulshake** [comment]
So far, I have been able to reproduce this only on GCE (sudo-enabled) builds. I would love to see a link to job where an `apt-get` command times out on EC2 (non-sudo), if anyone has one, especially if it shows the uptime of the machine.

My current theory is that `apt-get` commands are failing because the VM doesn't have network access yet, immediately after being created.

**Comment by dbudwin** [comment]
>Which infrastructure(s) are you experiencing this on (ec2, gce, jupiter)?
`hostname: f3b25140-1de7-44ac-8423-434f2db80660@1.production-1-worker-org-a-2-gce`
>Can you pinpoint when it started happening?
I've noticed for at least the past week or two, no exact date.
>At which point in your .travis.yml does this fail (before_install, script, addons.apt.packages, etc)?
My build isn't failing, but I'm investigating some side-effects of my build and I'm curious if this issue is related.
>Roughly how often does this occur (e.g. "1 in 10 jobs")
It goes through phases, sometimes it's every time, other times it happens less frequently.
>Have you found a reliable workaround?
No.  I haven't tried fixing this particular issue.
>Have you found a way to reliably reproduce?
No.  But if I rebuild a build enough times I can almost guarantee it'll happen.
>When it occurs, does it always cause the job to fail, or does the job succeed despite the error (or a mix of both)?
Still trying to determine this.  In one project a build is failing and I don't know why.  In another project with a similar structure to the first, the build passes even with this issue.  I think it's likely a problem with my build, but I don't this this issue is helping.

**Comment by kenkendk** [comment]
I have this on two different projects (both `gce`):
https://travis-ci.org/duplicati/duplicati/builds/336517696
https://travis-ci.org/kenkendk/sme/builds/336570247

> Can you pinpoint when it started happening?

Yes, Feb. 1st around 22:53 CET

> At which point in your .travis.yml does this fail (before_install, script, addons.apt.packages, etc)?

Not sure how it works, but it happens during the "install mono" part

> Roughly how often does this occur (e.g. "1 in 10 jobs")

After the initial fail, it happens consistently with new commits and restarts

> Have you found a reliable workaround?

No, not sure how I can add a boot delay as the failure happens before the contents from my `.travis.yml` file is handled

> Have you found a way to reliably reproduce?

Yes, it happens 100% consistently on the two repo's linked above

> When it occurs, does it always cause the job to fail, or does the job succeed despite the error (or a mix of both)?

Always fails because the required packages are not present on the system.

**Comment by rawlins** [comment]
We've been having this problem sporadically on https://github.com/crawl/crawl for some time now.

> Which infrastructure(s) are you experiencing this on (ec2, gce, jupiter)?

gce, trusty, sudo-enabled

> Can you pinpoint when it started happening?

It's been happening sporadically for over a month, possibly for the lifetime of the current trusty image. For example, [here](https://travis-ci.org/crawl/crawl/jobs/323075427)'s a build from early january that illustrates it.

> At which point in your .travis.yml does this fail (before_install, script, addons.apt.packages, etc)?

When this timeout happens, the builds error in before_install. But the timeout appears to be before that.

> Roughly how often does this occur (e.g. "1 in 10 jobs")

Possibly as much as 1 in 4 jobs (not all of our jobs will error though, see below).

> Have you found a reliable workaround? Have you found a way to reliably reproduce?

No to both (though it happens a lot).

When it occurs, does it always cause the job to fail, or does the job succeed despite the error (or a mix of both)?

Some of our jobs install libsdl2-dev. When the timeout happens, on those jobs, it appears that apt-get will have an old/wrong package list and this sets up the exact conditions for https://github.com/travis-ci/travis-ci/issues/8317 to happen (as long as the timeout happens, our build getting this error seems deterministic).  Our jobs that don't install libsdl2-dev don't typically error (though they may occasionally).

> Feel free to include the full line containing the error you receive

Here's a test build (on my fork) that as a bonus has a sleep command: https://travis-ci.org/rawlins/crawl/jobs/337601162

(On this fork I've temporarily enabled only jobs that install libsdl2-dev while trying to sort this out.)

> Does sleeping (say, sleep 30) before apt-get commands help?

Didn't help, see the above log.  You can see that the timeouts are happening even before the git clone during what appears to be the initial image setup (if I'm understanding things correctly), so the sleep command isn't going to do much.

**Comment by csm10495** [comment]
So far doing this:
```
sudo apt-get update --option Acquire::Retries=100 --option Acquire::http::Timeout="60"
```

To update has been working for me. It hasn't taken more than about ~21 seconds to update in total though. I figure the 60 second timeout is a worst case scenario (as are the retries).

**Comment by federeghe** [comment]
> Which infrastructure(s) are you experiencing this on (ec2, gce, jupiter)?

hostname: 7e67749c-b620-47f1-80c2-9eda5c3875c0@1.production-3-worker-com-c-1-gce

> Can you pinpoint when it started happening?

I started yesterday to build with Travis CI :) 

> At which point in your .travis.yml does this fail (before_install, script, addons.apt.packages, etc)?

`apt-get` failed to install. But the problem is at the beginning with a timeout in apt-get update:
`Unable to connect to ppa.launchpad.net:http:`

> Roughly how often does this occur (e.g. "1 in 10 jobs")

1 in 3 jobs

> Have you found a reliable workaround?

Just restart the job

> Have you found a way to reliably reproduce?

Randomly after some build

> When it occurs, does it always cause the job to fail, or does the job succeed despite the error (or a mix of both)?

The job continue after the timeout until `apt-get install` when it fails to install g++6

**Comment by pitrou** [comment]
Many apt-get failures currently:
https://travis-ci.org/apache/arrow/jobs/340607376
https://travis-ci.org/apache/arrow/jobs/340607378
https://travis-ci.org/apache/arrow/jobs/340607381
https://travis-ci.org/apache/arrow/jobs/340607382

**Comment by pitrou** [comment]
>   Which infrastructure(s) are you experiencing this on (ec2, gce, jupiter)?

For example `0dd023a5-64e4-40d0-9ae6-6d1c90494550@1.production-1-worker-org-b-1-gce`

>   Can you pinpoint when it started happening?

Not sure, but at least several weeks ago.

>    At which point in your .travis.yml does this fail (before_install, script, addons.apt.packages, etc)?

`addons.apt.packages` mostly, but sometimes in `before_script` as well.

>    Roughly how often does this occur (e.g. "1 in 10 jobs")

It's varying. Sometimes 1 in 50, sometimes 1 in 2...

>    Have you found a reliable workaround?

No :-(

>    Have you found a way to reliably reproduce?

No.

>    When it occurs, does it always cause the job to fail, or does the job succeed despite the error (or a mix of both)?

Not sure, since we don't notice if it doesn't cause the job to fail. But quite often the job fails indeed :-(

**Comment by rawlins** [comment]
I can confirm that something like this seems to be a workaround if added as the first command in before_install (haven't tweaked the timeout setting, but I have just a few example so far):

    sudo apt-get update --option Acquire::Retries=100 --option Acquire::http::Timeout="60"

For example, here's a successful build (well, it's not done yet, but it got past the crucial point in our apt script, so it should be fine) that has the timeout errors: https://travis-ci.org/rawlins/crawl/jobs/340632159

**Comment by pitrou** [comment]
Still many problems currently. It happens roughly 1 in 5 jobs.

**Comment by claremacrae** [comment]
I just got this on a build:
https://travis-ci.org/approvals/ApprovalTests.cpp/builds/348359381

The previous build used exactly the same infrastructure, and ran fine
https://travis-ci.org/approvals/ApprovalTests.cpp/builds/348009380

**Comment by stloeffler** [comment]
I'm also experiencing similar connection problems when _uploading_ to ppa.launchpad.net (via ftp when using dput): https://travis-ci.org/TeXworks/texworks/jobs/351031276#L2325 As I don't know how to increase the timeout using this method, I can't use the suggested workaround.

```
hostname: 48c15012-9b79-4cb9-a751-34d4330e2f40@1.production-4-worker-org-c-2-gce
First occurrence: March 8, 2018
Stage: deploy (script provider)
Frequency: every job so far (I restarted the corresponding build 3 times)
Reliable workaround: no
Reproducible: yes
Does the job fail: yes (the build succeeds, but deploying fails)
```

**Comment by BanzaiMan** [comment]
@stloeffler See http://manpages.ubuntu.com/manpages/bionic/en/man5/apt.conf.5.html for more details.

In more concrete terms: You can adding a file in `/etc/apt/apt.conf.d` (either overwrite `/etc/apt/apt.conf.d/37timeouts` or add a file that sorts *after* this file), or pass flags:

     sudo apt-get update --option Acquire::Retries="5" --option Acquire::http::Timeout="30"

**Comment by stloeffler** [comment]
@BanzaiMan Thanks for the info. However, I was not talking about downloading/installing packages _from_ Launchpad via `apt`, but rather about _uploading packages to Launchpad_ via `dput` (which uses ftp under the hood). I did see the apt options in the thread, but I don't know how to apply them to dput (and if that is possible and sensible at all).

**Comment by BanzaiMan** [comment]
@stloeffler OK. In that case, I suggest reading [`dput`(1)](http://manpages.ubuntu.com/manpages/precise/man1/dput.1.html) and [`dput.cf`(5)](http://manpages.ubuntu.com/manpages/precise/man5/dput.cf.5.html). I skimmed through them to look for timeouts and what not, I didn't see any. Maybe you have better eyes than mine.

**Comment by karalabe** [comment]
All PPA pushes started timing out for us to a week ago. Not a single went though. Never had this issue before.

**Comment by BanzaiMan** [comment]
Hello, there. We are continuing our investigation on this issue.

One thing we did find is that connections to ftp://ppa.launchpad.net is quite unreliable (estimating about 50% success rate). I reckon this explains the "push" issues @stloeffler and @karalabe mentioned.

The other issue (downloading manifests from http://ppa.launchpad.net) remains elusive; does anyone have a recent (last 2 days, say) build that failed to fetch files from ppa.launchpad.net (or any other server)?

**Comment by pevik** [comment]
@BanzaiMan we mostly have issues
`E: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release' is not signed.`

https://travis-ci.org/pevik/ltp/jobs/353420254
[log.pevik.353420254.txt](https://github.com/travis-ci/travis-ci/files/1812169/log.pevik.353420254.txt)

[log.ltp-test-project.353344932.txt](https://github.com/travis-ci/travis-ci/files/1812166/log.ltp-test-project.353344932.txt)

I tried to add workaround, but it didn't help much.
`sudo apt update --option Acquire::Retries=100 --option Acquire::http::Timeout="60"`
It would be great if travis become again reliable.

**Comment by rawlins** [comment]
>The other issue (downloading manifests from http://ppa.launchpad.net) remains elusive; does anyone have a recent (last 2 days, say) build that failed to fetch files from ppa.launchpad.net (or any other server)?

I just restarted a build on my test repo a bunch of times and can no longer replicate it on demand (I more or less could before), so maybe something's improved with ppa.launchpad.net, or maybe there are other conditions. If I think of it, I'll try again tonight. The most recent one for ppa.launchpad.net errors we have is 14 days ago (where the timeout wasn't long enough I guess): https://travis-ci.org/crawl/crawl/jobs/347360333. But there haven't been very many commits to this repo in the last few days.

However, here's a build from earlier today with timeout errors for packagecloud.io and mongodb.org (didn't error; the apt-get workaround in before_install looks like it successfully connected): https://travis-ci.org/crawl/crawl/jobs/353375037

I do occasionally and randomly see signing errors for mongodb (usually key expired), but I've definitely seen these without timeout errors, so I'm not sure if it's really the same issue, or if a workaround that does `apt-get update` will be likely to help with it.

**Comment by BanzaiMan** [comment]
Hello, everyone.

We continue to investigate this issue, and would like further input. Have you seen HTTP connection problems on GCE (`sudo: required`) builds in the past couple of weeks? If so, could you paste the build log URLs, or email them to support@travis-ci.com?

FTP appears to be a persistent problems, and we have plenty of information to dig deeper into that issue.

Again, thank you for your continued patience.

**Comment by BanzaiMan** [comment]
For FTP issues, adding retries and timeouts might help. With `curl`:

    curl --retry 4 --connect-timeout 20 ftp://…

If your utility does not have convenient ways to achieve this, you'd have to come up with your own mechanism to achieve similar effects.

We have contacted our service providers to dig deeper into this issue.

Thank you.

**Comment by BanzaiMan** [comment]
I'm going to move discussion on issues related to FTP tohttps://github.com/travis-ci/travis-ci/issues/9391. This issue remains focused on APT package index fetching failures.

**Comment by BanzaiMan** [comment]
Hello, everyone.

# TL;DR

Please try:

```yaml
addons:
  apt:
    config:
      retries: true
    ⋮ # rest (including `packages` and `sources`, if applicable
```

and report results, please.

# Details

We have just deployed https://github.com/travis-ci/travis-build/pull/1343. This PR adds an opt-in configuration option to the `apt` addon, so that `apt-get install` gets 3 options that will hopefully reduce the effects of this problem we are seeing.

Namely, it adds the configuration file `/etc/apt/apt.conf.d/99-travis-build-retries` with the content:

```
Acquire {
  ForceIPv4 "1";
  Retries "5";
  https {
    Timeout "30";
  };
};
```

The desired effect is to force IPv4 connection, with timeout of 30 seconds, and retries up to 5 times if the request times out.

This is not a true resolution, but hopefully good enough for you while we continue investigation.

**Comment by gornostal** [comment]
I found a way to reliably reproduce this issue by using lfpt and uploading files larger 1Mb to ppa.launchpad.net.
I hope [this github repo](https://github.com/gornostal/launchpad-ftp-test) with simple travis.yml and Dockerfile will be helpful.

P.S. Travis CI rocks! It is so easy to automate builds and deployment with Travis. Thank you guys :+1:

**Comment by gornostal** [comment]
Has anyone looked at this issue?
Travis jobs still fail to publish packages to Launchpad :(

**Comment by benlindsay** [comment]
First, let me echo @gornostal that Travis is very cool. I just started playing with it and I'm excited to incorporate this tool into more of my github repos.

However I'm seeing the same issue of inconsistent connection to Launchpad, which leads to inconsistent results. As a simple test, I set up a [github repo](https://github.com/benlindsay/travis-addon-test) with nothing but a `README.md` and a `.travis.yml` file. The travis file looks like this:

```
sudo: required
dist: trusty
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env:
        - VERSION='4.8'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - VERSION='4.9'
...
script: echo "That's all!"
```

There are a few other g++ versions hidden in that `...`.  On one build (link [here](https://travis-ci.org/benlindsay/travis-addon-test/builds/385295907)), version 5 and version 8 fail to connect to Launchpad. Then I added a blank line in `README.md` as a dummy change, committed it, and pushed it. The travis jobs resulting from that are [here](https://travis-ci.org/benlindsay/travis-addon-test/builds/385296135), where versions 6, 7, and 8 fail, but versions 4.8, 4.9, and 5 succeed.

As a newcomer to Travis, this has been quite frustrating, since I expected to be able to trust the basic environment setup stuff and use the tool to figure out where my code is bad. Is there any plan to fix this, or is there some workaround I can use to get reliable results?

**Comment by benlindsay** [comment]
Update: today all of my tests are passing with no change to my code. Not sure if there's a permanent fix that is responsible for this or if today there is less traffic stressing the network, but hopefully these tests continue to succeed :)

**Comment by tbarbette** [comment]
This is getting annoying. Around 1/3rd of my jobs fails because of this. This issue is very old though.

```
Err:14 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 g++-4.8 amd64 4.8.5-4ubuntu8~14.04.2
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:15 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 gcc-4.8 amd64 4.8.5-4ubuntu8~14.04.2
  Unable to connect to ppa.launchpad.net:http:
Err:16 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 cpp-4.8 amd64 4.8.5-4ubuntu8~14.04.2
  Unable to connect to ppa.launchpad.net:http:
Err:17 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libstdc++-4.8-dev amd64 4.8.5-4ubuntu8~14.04.2
  Unable to connect to ppa.launchpad.net:http:
Err:18 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libtsan0 amd64 8.1.0-5ubuntu1~14.04
  Unable to connect to ppa.launchpad.net:http:
Err:19 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libquadmath0 amd64 8.1.0-5ubuntu1~14.04
  Unable to connect to ppa.launchpad.net:http:
Err:20 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libgcc-4.8-dev amd64 4.8.5-4ubuntu8~14.04.2
  Unable to connect to ppa.launchpad.net:http:
Err:21 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libasan0 amd64 4.8.5-4ubuntu8~14.04.2
  Unable to connect to ppa.launchpad.net:http:
Err:22 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 gcc-4.8-base amd64 4.8.5-4ubuntu8~14.04.2
  Unable to connect to ppa.launchpad.net:http:
Fetched 11.0 MB in 15s (727 kB/s)
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-4.8/g++-4.8_4.8.5-4ubuntu8~14.04.2_amd64.deb  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-4.8/gcc-4.8_4.8.5-4ubuntu8~14.04.2_amd64.deb  Unable to connect to ppa.launchpad.net:http:
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-4.8/cpp-4.8_4.8.5-4ubuntu8~14.04.2_amd64.deb  Unable to connect to ppa.launchpad.net:http:
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-4.8/libstdc++-4.8-dev_4.8.5-4ubuntu8~14.04.2_amd64.deb  Unable to connect to ppa.launchpad.net:http:
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-8/libtsan0_8.1.0-5ubuntu1~14.04_amd64.deb  Unable to connect to ppa.launchpad.net:http:
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-8/libquadmath0_8.1.0-5ubuntu1~14.04_amd64.deb  Unable to connect to ppa.launchpad.net:http:
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-4.8/libgcc-4.8-dev_4.8.5-4ubuntu8~14.04.2_amd64.deb  Unable to connect to ppa.launchpad.net:http:
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-4.8/libasan0_4.8.5-4ubuntu8~14.04.2_amd64.deb  Unable to connect to ppa.launchpad.net:http:
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-4.8/gcc-4.8-base_4.8.5-4ubuntu8~14.04.2_amd64.deb  Unable to connect to ppa.launchpad.net:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by JasonGross** [comment]
This came up again.  The log ([it was here, before I restarted the job](https://travis-ci.org/mit-plv/fiat-crypto/jobs/414339272), and [here is a gist of the raw log](https://gist.github.com/JasonGross/4171919976af2b2b4d96455cd407e1e5)) ends with:
```
Get:1 http://ppa.launchpad.net/jgross-h/coq-master-daily/ubuntu trusty/main amd64 coq-theories amd64 8.master~git~201808071518+19428-0~daily314~ubuntu14.04.1 [20.2 MB]
Get:2 http://ppa.launchpad.net/jgross-h/coq-master-daily/ubuntu trusty/main amd64 liblablgtksourceview2-ocaml amd64 2.18.3+dfsg-1build1~ubuntu14.04.1~ppa1 [94.9 kB]
Get:3 http://ppa.launchpad.net/jgross-h/coq-master-daily/ubuntu trusty/main amd64 libcoq-ocaml amd64 8.master~git~201808071518+19428-0~daily314~ubuntu14.04.1 [5,657 kB]
Get:4 http://ppa.launchpad.net/jgross-h/coq-master-daily/ubuntu trusty/main amd64 coq amd64 8.master~git~201808071518+19428-0~daily314~ubuntu14.04.1 [17.2 MB]
Get:5 http://ppa.launchpad.net/jgross-h/coq-master-daily/ubuntu trusty/main amd64 coqide amd64 8.master~git~201808071518+19428-0~daily314~ubuntu14.04.1 [7,478 kB]
Get:6 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 cpp-7 amd64 7.3.0-21ubuntu1~14.04 [6,655 kB]
Get:7 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libgcc-7-dev amd64 7.3.0-21ubuntu1~14.04 [2,373 kB]
Get:8 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 gcc-7 amd64 7.3.0-21ubuntu1~14.04 [7,353 kB]
Ign:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libstdc++-7-dev amd64 7.3.0-21ubuntu1~14.04
Ign:10 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 g++-7 amd64 7.3.0-21ubuntu1~14.04
Ign:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libstdc++-7-dev amd64 7.3.0-21ubuntu1~14.04
Ign:10 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 g++-7 amd64 7.3.0-21ubuntu1~14.04
Err:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 libstdc++-7-dev amd64 7.3.0-21ubuntu1~14.04
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:10 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 g++-7 amd64 7.3.0-21ubuntu1~14.04
  Unable to connect to ppa.launchpad.net:http:
Fetched 54.2 MB in 1min 18s (687 kB/s)
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-7/libstdc++-7-dev_7.3.0-21ubuntu1~14.04_amd64.deb  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-7/g++-7_7.3.0-21ubuntu1~14.04_amd64.deb  Unable to connect to ppa.launchpad.net:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command "sudo apt-get install g++-7 libssl-dev coq -y --allow-unauthenticated" failed 3 times.
The command "travis_retry sudo apt-get install g++-7 libssl-dev $COQ_PACKAGE -y --allow-unauthenticated" failed and exited with 100 during .
```

**Comment by jay** [comment]
Is it possible this is caused by the VMs slowing down to the point that they are unusable, and is not a network issue? (Put aside [this known issue](https://twitter.com/traviscistatus/status/1028016677298946048) for the moment) We have retries enabled (curl/curl@d267dd2) but get these errors. Also rarely some curl tests fail will arbitrarily on timeout. So I wonder if there's something else going on.

/cc @bagder

**Comment by claremacrae** [comment]
@BanzaiMan That's great - thank you. What was the nature of the fix please?

**Comment by WaleedAshraf** [comment]
Thanks all whoever worked on this. It been 9 months. For me, I found a way out by making some changes in config (as far as i remember) and at one point I just unwatched this issue.

I hope it's actually fixed for everyone.

**Comment by JasonGross** [comment]
This is definitely not fixed, please re-open the issue.  Here is another instance of it from 5 hours ago: https://travis-ci.org/mit-plv/fiat-crypto/jobs/440367055
```
 travis_retry ./etc/ci/sudo-apt-get-update.sh -q
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Ign:2 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
Ign:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu trusty InRelease
Hit:4 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release
Get:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu trusty-updates InRelease [65.9 kB]
Hit:8 http://security.ubuntu.com/ubuntu trusty-security InRelease
Hit:10 http://us-east-1.ec2.archive.ubuntu.com/ubuntu trusty-backports InRelease
Ign:6 http://toolbelt.heroku.com/ubuntu ./ InRelease
Hit:11 http://us-east-1.ec2.archive.ubuntu.com/ubuntu trusty Release
Hit:12 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease
Hit:13 https://download.docker.com/linux/ubuntu trusty InRelease
Hit:16 https://dl.hhvm.com/ubuntu trusty InRelease
Hit:14 http://toolbelt.heroku.com/ubuntu ./ Release
Hit:17 http://dl.google.com/linux/chrome/deb stable Release
Get:15 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Ign:18 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Get:23 http://ppa.launchpad.net/jgross-h/coq-master-daily/ubuntu trusty InRelease [16.0 kB]
Get:26 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty InRelease [15.4 kB]
Get:9 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease [15.4 kB]
Get:28 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release [15.1 kB]
Get:20 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease [15.4 kB]
Get:29 http://ppa.launchpad.net/jgross-h/coq-master-daily/ubuntu trusty/main amd64 Packages [8,159 B]
Get:30 http://ppa.launchpad.net/jgross-h/coq-master-daily/ubuntu trusty/main i386 Packages [8,145 B]
Get:31 http://ppa.launchpad.net/jgross-h/coq-master-daily/ubuntu trusty/main Translation-en [5,723 B]
Get:24 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease [15.4 kB]
Get:25 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease [15.4 kB]
Err:32 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
  Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out
Hit:33 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
Hit:34 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease
Ign:35 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 Packages
Ign:36 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main i386 Packages
Ign:37 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main Translation-en
Err:27 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
  Unable to connect to ppa.launchpad.net:http:
Ign:38 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages
Ign:39 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages
Ign:40 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main Translation-en
Err:41 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release.gpg
  Unable to connect to ppa.launchpad.net:http:
Ign:42 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main amd64 Packages
Ign:43 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main i386 Packages
Ign:44 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main Translation-en
Ign:45 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main amd64 Packages
Ign:46 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main i386 Packages
Ign:47 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main Translation-en
Ign:48 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main amd64 Packages
Ign:49 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages
Ign:50 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main Translation-en
Ign:35 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 Packages
Ign:36 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main i386 Packages
Ign:37 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main Translation-en
Ign:38 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages
Ign:39 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages
Ign:40 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main Translation-en
Ign:51 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main amd64 Packages
Ign:52 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main i386 Packages
Ign:53 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main Translation-en
Ign:42 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main amd64 Packages
Ign:43 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main i386 Packages
Ign:44 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main Translation-en
Ign:45 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main amd64 Packages
Ign:46 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main i386 Packages
Ign:47 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main Translation-en
Ign:48 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main amd64 Packages
Ign:49 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages
Ign:50 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main Translation-en
Err:35 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 Packages
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:36 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main i386 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:37 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main Translation-en
  Unable to connect to ppa.launchpad.net:http:
Err:38 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:39 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:40 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main Translation-en
  Unable to connect to ppa.launchpad.net:http:
Ign:51 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main amd64 Packages
Ign:52 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main i386 Packages
Ign:53 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main Translation-en
Err:42 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main amd64 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:43 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main i386 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:44 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main Translation-en
  Unable to connect to ppa.launchpad.net:http:
Err:45 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main amd64 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:46 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main i386 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:47 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main Translation-en
  Unable to connect to ppa.launchpad.net:http:
Err:48 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main amd64 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:49 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:50 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main Translation-en
  Unable to connect to ppa.launchpad.net:http:
Err:51 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main amd64 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:52 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main i386 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:53 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main Translation-en
  Unable to connect to ppa.launchpad.net:http:
Fetched 199 kB in 14s (14.1 kB/s)
Reading package lists...
W: The repository 'http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release' is not signed.
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/main/binary-amd64/Packages  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by JasonGross** [comment]
Note that the log I linked to retries the apt-get command three times, and all three of them failed.

**Comment by BanzaiMan** [comment]
@JasonGross Probably this incident: https://www.traviscistatus.com/incidents/zmw37lfzk3p3

**Comment by tbarbette** [comment]
No it's not. With sudo not required it happened to me already multiple times today.

**Comment by pevik** [comment]
Broken for long time (at least for 9 months), not progress and ticket closed. With approach like this we should probably switch to another service :(

**Comment by mteguhfh** [comment]
Untill today, i have this issue.

sudo apt-get update
[sudo] password for mteguhfh:          
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease                                                    
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]                                     
Hit:3 http://packages.elementary.io/appcenter bionic InRelease                                                  
Hit:4 http://dl.google.com/linux/chrome/deb stable Release                                                      
Hit:5 http://id.archive.ubuntu.com/ubuntu bionic InRelease                                                      
Get:7 http://id.archive.ubuntu.com/ubuntu bionic-updates InRelease [88,7 kB]                                    
Get:8 http://id.archive.ubuntu.com/ubuntu bionic-backports InRelease [74,6 kB]                      
Err:9 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic InRelease                                     
  Could not connect to ppa.launchpad.net:80 (91.189.95.83). - connect (111: Connection refused)
Err:10 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease                                
  Unable to connect to ppa.launchpad.net:http:
Fetched 247 kB in 7s (33,8 kB/s)                                                                                
Reading package lists... Done
W: Failed to fetch http://ppa.launchpad.net/elementary-os/stable/ubuntu/dists/bionic/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83). - connect (111: Connection refused)
W: Failed to fetch http://ppa.launchpad.net/elementary-os/os-patches/ubuntu/dists/bionic/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by BanzaiMan** [comment]
@mteguhfh Where do you see this?

**Comment by mteguhfh** [comment]
> @mteguhfh Where do you see this?

in Elementary JUNO, i want to update but got error in appcenter too

**Comment by BanzaiMan** [comment]
@mteguhfh Sorry, what does that mean? Do you have a build log URL that shows this problem?

**Comment by tbarbette** [comment]
Well this issue is still basically everywhere...

**Comment by BanzaiMan** [comment]
> Well this issue is still basically everywhere...

Please include the build log URL. Thanks.

**Comment by rawlins** [comment]
@tbarbette we haven't had this problem since instituting one of the fixes earlier in this thread, and definitely not since the issue was closed, except for occasional problems that are not on the travis side. (Our builds originally had ppa.launchpad.net problems quite regularly.) So you're probably going to have to give them a bit more to work with...

**Comment by tbarbette** [comment]
I'll do so when I'll catch it again. I relaunch the test manually when it happens so not sure where to get the log now.
Sorry, multiple people said it was still happening, therefore I did not bother to resend the log again.
@rawlins retries definitely helped, but it's just a matter of being more lucky for one of the tries.

**Comment by meatballhat** [comment]
Hello, all! We recently shipped a change to the Linux build execution infrastructure that makes use of a region-local HTTP cache for APT. The use of this cache is dynamic based on availability at the beginning of a job, and is currently _only_ for the APT `http` transport. Implementation exists in a few separate repositories, but [this is the build-time code](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/bash/travis_setup_apt_proxy.bash).

**Comment by cotsog** [comment]
The new APT proxy should be transparent and used on every build (depending on availability). If you are still seeing this issue, could you post relevant build links/URLs? We would be happy to have a look.

Thanks!

(/cc @pevik from [this comment](https://github.com/travis-ci/travis-build/pull/1606#issuecomment-447343182) on https://github.com/travis-ci/travis-build/pull/1606)

**Comment by bsipocz** [comment]
We've hit this issue for a while in a private repo that used sudo-enabled infrastructure. As of today, I've  switched it to use the non sudo approach and the build is working again.

**Comment by tbarbette** [comment]
It is fixed on our side for quite some time now. I guess it took some days to be effective everywhere.

**Comment by bsipocz** [comment]
@tbarbette - It was still failing *today* on fresh commits, and this is why I mentioned it above.

**Comment by BanzaiMan** [comment]
@bsipocz Could you email us at support@travis-ci.com with details? It would be good to investigate, if the issue still persists.

**Comment by igsilya** [comment]
Hi. Sorry for resurrecting this thread, but this issue frequently happens to me with apt cache connection timeout via apt addon:
`E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gccgo-6/gcc-6-base_6.0.1-0ubuntu1_i386.deb  Unable to connect to apt.cache.travis-ci.com:http:`
This happens for Xenial builds, don't see that much with Trusty.
Issue frequency is about 1 of 10 jobs which is annoying because project has ~20 jobs in a single run.
Recently failed job: https://travis-ci.org/ovsrobot/ovs/jobs/568340146

**Comment by Kami** [comment]
Same here.

This issue started appearing again for our StackStorm/st2 builds on Friday. It happens very often for most of our builds and it's almost impossible to get builds to pass because of this issue.

Here is an example of such build - https://travis-ci.org/StackStorm/st2/jobs/574431900 (I already contacted support@, but haven't heard back yet).

To try to work around this issue, I moved away from apt addon back to manually running apt-get commands with increased timeout - https://github.com/StackStorm/st2/pull/4772

The workaround seems to be working, but it's far from ideal since apt-get update now takes a long time.
