### ISSUE TITLE
OS X pandoc url is wrong for R packages

### ISSUE THREAD

**Issue by dongzhuoer** [travis-ci/travis-ci#9367]
at least for 2.1.2, the url should be https://github.com/jgm/pandoc/releases/download/2.1.2/pandoc-2.1.2-macOS.pkg instead of https://github.com/jgm/pandoc/releases/download/2.1.2/pandoc-2.1.2-osx.pkg

https://travis-ci.org/dongzhuoer/zhuoerdown/jobs/355689693#0-69

**Comment by BanzaiMan** [comment]
Please mention @craigcitro and @jimhester for R inquiries, as indicated in the build log. Thank you.

**Comment by Zialus** [comment]
This problem still stands with pandoc 2.2.

Travis tries to download https://github.com/jgm/pandoc/releases/download/2.2/pandoc-2.2-osx.pkg
but the correct url would be https://github.com/jgm/pandoc/releases/download/2.2/pandoc-2.2-macOS.pkg

**Comment by coatless** [comment]
FYI: This should be resolved in https://github.com/travis-ci/travis-build/pull/1373

In addition, the default for pandoc is bumped to v2.2

**Comment by coatless** [comment]
This can be closed out as travis-ci/travis-build#1373 and travis-ci/docs-travis-ci-com#1827 have been merged in.

**Comment by dongzhuoer** [comment]
Does it take a long time to take effect?

I still see it fail for 2.1 (https://travis-ci.com/dongzhuoer/zhuoerdown/jobs/123493651, line 83), 2.2(https://travis-ci.com/dongzhuoer/zhuoerdown/jobs/123494177, line 83), and the default version is still 1.15.2(https://travis-ci.com/dongzhuoer/zhuoerdown/jobs/123494764, line 79)

**Comment by coatless** [comment]
Not entirely sure how long it takes to replicate out. But, the change is definitely in.
